In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [2]:
df=pd.read_csv('D:\genai\Machine learning\ML\Mumbai_University_KT_Students_Dataset.csv')

<>:1: SyntaxWarning: "\g" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\g"? A raw string is also an option.
<>:1: SyntaxWarning: "\g" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\g"? A raw string is also an option.
C:\Users\hites\AppData\Local\Temp\ipykernel_924\1049918973.py:1: SyntaxWarning: "\g" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\g"? A raw string is also an option.
  df=pd.read_csv('D:\genai\Machine learning\ML\Mumbai_University_KT_Students_Dataset.csv')

In [3]:
df.head()

,Student_ID,Age,Gender,Branch,Year_of_Study,Commute_Mode,Commute_Time_mins,Attendance_Percentage,Study_Hours_per_Day,Social_Media_Hours_per_Day,...,Part_Time_Job,Extracurricular_Activities,Peer_Learning,Mentorship_Available,Financial_Status,Previous_Semester_SGPA,Stress_Level,Number_of_KTs,Has_KT,Cleared_in_First_Attempt
0,MU00001,24,Male,Information Technology,Second Year,Local Train,85,67,3.7,2.6,...,No,Yes,Yes,No,Middle Class,6.79,High,4,Yes,No
1,MU00002,21,Female,Information Technology,Final Year,Local Train,92,100,1.7,3.8,...,No,Yes,Yes,No,Lower Middle Class,5.76,Low,0,No,Yes
2,MU00003,19,Female,Electronics & Telecom (EXTC),Second Year,Two-Wheeler,50,40,3.4,3.2,...,Yes,No,No,Yes,Middle Class,4.73,High,3,Yes,No
3,MU00004,22,Female,Mechanical Engineering,Second Year,Local Train,88,85,3.9,3.5,...,No,No,Yes,Yes,Middle Class,6.15,Low,0,No,Yes
4,MU00005,23,Male,Electronics & Telecom (EXTC),Final Year,Local Train,83,64,2.6,3.7,...,Yes,No,No,No,Middle Class,3.89,High,4,Yes,No

In [4]:
df.isnull().sum()

Student_ID                      0
Age                             0
Gender                          0
Branch                          0
Year_of_Study                   0
Commute_Mode                    0
Commute_Time_mins               0
Attendance_Percentage           0
Study_Hours_per_Day           207
Social_Media_Hours_per_Day    221
Sleep_Hours_per_Night         181
Part_Time_Job                   0
Extracurricular_Activities      0
Peer_Learning                   0
Mentorship_Available            0
Financial_Status                0
Previous_Semester_SGPA        204
Stress_Level                    0
Number_of_KTs                   0
Has_KT                          0
Cleared_in_First_Attempt        0
dtype: int64

In [5]:
df.columns

Index(['Student_ID', 'Age', 'Gender', 'Branch', 'Year_of_Study',
       'Commute_Mode', 'Commute_Time_mins', 'Attendance_Percentage',
       'Study_Hours_per_Day', 'Social_Media_Hours_per_Day',
       'Sleep_Hours_per_Night', 'Part_Time_Job', 'Extracurricular_Activities',
       'Peer_Learning', 'Mentorship_Available', 'Financial_Status',
       'Previous_Semester_SGPA', 'Stress_Level', 'Number_of_KTs', 'Has_KT',
       'Cleared_in_First_Attempt'],
      dtype='str')

In [6]:
df['Study_Hours_per_Day'].unique()

array([3.7, 1.7, 3.4, 3.9, 2.6, 2.3, 3. , 3.2, 3.1, 2.9, 3.6, 4. , 2.7,
       2.8, 2.5, 0. , 3.5, 5.7, 2.1, 4.9, 1.3, 0.9, 0.3, 6.1, 4.8, 3.3,
       4.1, 4.3, 5.8, 1.6, nan, 5.9, 5.4, 1.5, 2.4, 0.8, 1.4, 4.4, 7. ,
       4.7, 2. , 1.2, 1.1, 2.2, 1.8, 4.2, 5.2, 3.8, 4.6, 5.3, 0.7, 1.9,
       4.5, 0.4, 0.2, 0.5, 5. , 5.6, 1. , 5.1, 0.6, 6.4, 6. , 0.1, 6.3,
       8.5, 5.5, 7.2, 7.7, 6.8, 7.3, 6.9, 6.2, 6.7, 6.6, 7.9, 6.5, 7.4,
       7.6, 7.1])

In [7]:
df['Study_Hours_per_Day']=df['Study_Hours_per_Day'].fillna(df['Study_Hours_per_Day'].median())
df['Social_Media_Hours_per_Day']=df['Social_Media_Hours_per_Day'].fillna(df['Social_Media_Hours_per_Day'].median())
df['Sleep_Hours_per_Night']=df['Sleep_Hours_per_Night'].fillna(df['Sleep_Hours_per_Night'].median())
df['Previous_Semester_SGPA']=df['Previous_Semester_SGPA'].fillna(df['Previous_Semester_SGPA'].median())

In [8]:
df.isnull().sum()

Student_ID                    0
Age                           0
Gender                        0
Branch                        0
Year_of_Study                 0
Commute_Mode                  0
Commute_Time_mins             0
Attendance_Percentage         0
Study_Hours_per_Day           0
Social_Media_Hours_per_Day    0
Sleep_Hours_per_Night         0
Part_Time_Job                 0
Extracurricular_Activities    0
Peer_Learning                 0
Mentorship_Available          0
Financial_Status              0
Previous_Semester_SGPA        0
Stress_Level                  0
Number_of_KTs                 0
Has_KT                        0
Cleared_in_First_Attempt      0
dtype: int64

In [9]:
df['Study_Hours_per_Day'].unique()

array([3.7, 1.7, 3.4, 3.9, 2.6, 2.3, 3. , 3.2, 3.1, 2.9, 3.6, 4. , 2.7,
       2.8, 2.5, 0. , 3.5, 5.7, 2.1, 4.9, 1.3, 0.9, 0.3, 6.1, 4.8, 3.3,
       4.1, 4.3, 5.8, 1.6, 5.9, 5.4, 1.5, 2.4, 0.8, 1.4, 4.4, 7. , 4.7,
       2. , 1.2, 1.1, 2.2, 1.8, 4.2, 5.2, 3.8, 4.6, 5.3, 0.7, 1.9, 4.5,
       0.4, 0.2, 0.5, 5. , 5.6, 1. , 5.1, 0.6, 6.4, 6. , 0.1, 6.3, 8.5,
       5.5, 7.2, 7.7, 6.8, 7.3, 6.9, 6.2, 6.7, 6.6, 7.9, 6.5, 7.4, 7.6,
       7.1])

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Student_ID                  10000 non-null  str
 1   Age                         10000 non-null  int64
 2   Gender                      10000 non-null  str
 3   Branch                      10000 non-null  str
 4   Year_of_Study               10000 non-null  str
 5   Commute_Mode                10000 non-null  str
 6   Commute_Time_mins           10000 non-null  int64
 7   Attendance_Percentage       10000 non-null  int64
 8   Study_Hours_per_Day         10000 non-null  float64
 9   Social_Media_Hours_per_Day  10000 non-null  float64
 10  Sleep_Hours_per_Night       10000 non-null  float64
 11  Part_Time_Job               10000 non-null  str
 12  Extracurricular_Activities  10000 non-null  str
 13  Peer_Learning               10000 non-null  str
 14  Mentorship_Available        10000 non-null  str
 15  Financial_Status            10000 non-null  str
 16  Previous_Semester_SGPA      10000 non-null  float64
 17  Stress_Level                10000 non-null  str
 18  Number_of_KTs               10000 non-null  int64
 19  Has_KT                      10000 non-null  str
 20  Cleared_in_First_Attempt    10000 non-null  str
dtypes: float64(4), int64(4), str(13)
memory usage: 1.6 MB

In [11]:
df.head()

,Student_ID,Age,Gender,Branch,Year_of_Study,Commute_Mode,Commute_Time_mins,Attendance_Percentage,Study_Hours_per_Day,Social_Media_Hours_per_Day,...,Part_Time_Job,Extracurricular_Activities,Peer_Learning,Mentorship_Available,Financial_Status,Previous_Semester_SGPA,Stress_Level,Number_of_KTs,Has_KT,Cleared_in_First_Attempt
0,MU00001,24,Male,Information Technology,Second Year,Local Train,85,67,3.7,2.6,...,No,Yes,Yes,No,Middle Class,6.79,High,4,Yes,No
1,MU00002,21,Female,Information Technology,Final Year,Local Train,92,100,1.7,3.8,...,No,Yes,Yes,No,Lower Middle Class,5.76,Low,0,No,Yes
2,MU00003,19,Female,Electronics & Telecom (EXTC),Second Year,Two-Wheeler,50,40,3.4,3.2,...,Yes,No,No,Yes,Middle Class,4.73,High,3,Yes,No
3,MU00004,22,Female,Mechanical Engineering,Second Year,Local Train,88,85,3.9,3.5,...,No,No,Yes,Yes,Middle Class,6.15,Low,0,No,Yes
4,MU00005,23,Male,Electronics & Telecom (EXTC),Final Year,Local Train,83,64,2.6,3.7,...,Yes,No,No,No,Middle Class,3.89,High,4,Yes,No

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.columns

Index(['Student_ID', 'Age', 'Gender', 'Branch', 'Year_of_Study',
       'Commute_Mode', 'Commute_Time_mins', 'Attendance_Percentage',
       'Study_Hours_per_Day', 'Social_Media_Hours_per_Day',
       'Sleep_Hours_per_Night', 'Part_Time_Job', 'Extracurricular_Activities',
       'Peer_Learning', 'Mentorship_Available', 'Financial_Status',
       'Previous_Semester_SGPA', 'Stress_Level', 'Number_of_KTs', 'Has_KT',
       'Cleared_in_First_Attempt'],
      dtype='str')

In [14]:
df=df[['Student_ID', 'Age', 'Gender', 'Branch', 'Year_of_Study'
       ,  'Attendance_Percentage',
       'Study_Hours_per_Day', 'Social_Media_Hours_per_Day',
       'Sleep_Hours_per_Night', 
        'Financial_Status',
       'Previous_Semester_SGPA', 'Stress_Level', 'Number_of_KTs', 'Has_KT',
       'Cleared_in_First_Attempt']]

In [15]:
df.head()

,Student_ID,Age,Gender,Branch,Year_of_Study,Attendance_Percentage,Study_Hours_per_Day,Social_Media_Hours_per_Day,Sleep_Hours_per_Night,Financial_Status,Previous_Semester_SGPA,Stress_Level,Number_of_KTs,Has_KT,Cleared_in_First_Attempt
0,MU00001,24,Male,Information Technology,Second Year,67,3.7,2.6,4.8,Middle Class,6.79,High,4,Yes,No
1,MU00002,21,Female,Information Technology,Final Year,100,1.7,3.8,7.1,Lower Middle Class,5.76,Low,0,No,Yes
2,MU00003,19,Female,Electronics & Telecom (EXTC),Second Year,40,3.4,3.2,7.1,Middle Class,4.73,High,3,Yes,No
3,MU00004,22,Female,Mechanical Engineering,Second Year,85,3.9,3.5,6.9,Middle Class,6.15,Low,0,No,Yes
4,MU00005,23,Male,Electronics & Telecom (EXTC),Final Year,64,2.6,3.7,7.3,Middle Class,3.89,High,4,Yes,No

In [16]:
from sklearn.preprocessing import LabelEncoder

In [17]:
le=LabelEncoder()
df['Student_ID']=le.fit_transform(df['Student_ID'])
df['Gender']=le.fit_transform(df['Gender'])
df['Branch']=le.fit_transform(df['Branch'])
df['Year_of_Study']=le.fit_transform(df['Year_of_Study'])
df['Financial_Status']=le.fit_transform(df['Financial_Status'])
df['Stress_Level']=le.fit_transform(df['Stress_Level'])
df['Has_KT']=le.fit_transform(df['Has_KT'])
df['Cleared_in_First_Attempt']=le.fit_transform(df['Cleared_in_First_Attempt'])

In [18]:
df.head()

,Student_ID,Age,Gender,Branch,Year_of_Study,Attendance_Percentage,Study_Hours_per_Day,Social_Media_Hours_per_Day,Sleep_Hours_per_Night,Financial_Status,Previous_Semester_SGPA,Stress_Level,Number_of_KTs,Has_KT,Cleared_in_First_Attempt
0,0,24,1,5,2,67,3.7,2.6,4.8,1,6.79,0,4,1,0
1,1,21,0,5,0,100,1.7,3.8,7.1,0,5.76,1,0,0,1
2,2,19,0,4,2,40,3.4,3.2,7.1,1,4.73,0,3,1,0
3,3,22,0,6,2,85,3.9,3.5,6.9,1,6.15,1,0,0,1
4,4,23,1,4,0,64,2.6,3.7,7.3,1,3.89,0,4,1,0

In [19]:
df.columns

Index(['Student_ID', 'Age', 'Gender', 'Branch', 'Year_of_Study',
       'Attendance_Percentage', 'Study_Hours_per_Day',
       'Social_Media_Hours_per_Day', 'Sleep_Hours_per_Night',
       'Financial_Status', 'Previous_Semester_SGPA', 'Stress_Level',
       'Number_of_KTs', 'Has_KT', 'Cleared_in_First_Attempt'],
      dtype='str')

In [20]:
X=df[['Student_ID', 'Age', 'Gender', 'Branch', 'Year_of_Study',
       'Attendance_Percentage', 'Study_Hours_per_Day',
       'Social_Media_Hours_per_Day', 'Sleep_Hours_per_Night',
       'Financial_Status', 'Previous_Semester_SGPA', 'Stress_Level',
        'Has_KT', 'Cleared_in_First_Attempt']]

In [67]:
df['Number_of_KTs'].unique()

array([4, 0, 3, 2, 1, 5, 7, 6])

In [21]:
Y=df['Number_of_KTs']

In [22]:
from sklearn.preprocessing import StandardScaler
s=StandardScaler()

In [23]:
X=s.fit_transform(X)

In [24]:
X

array([[-1.73187761,  1.47492851,  0.72103451, ..., -1.66051835,
         0.5909006 , -0.5909006 ],
       [-1.7315312 , -0.00895275, -1.20480553, ..., -0.20927001,
        -1.69233201,  1.69233201],
       [-1.73118479, -0.99820693, -1.20480553, ..., -1.66051835,
         0.5909006 , -0.5909006 ],
       ...,
       [ 1.73118479, -0.99820693, -1.20480553, ..., -0.20927001,
        -1.69233201,  1.69233201],
       [ 1.7315312 , -0.99820693,  0.72103451, ..., -0.20927001,
        -1.69233201,  1.69233201],
       [ 1.73187761, -0.99820693,  0.72103451, ...,  1.24197833,
         0.5909006 , -0.5909006 ]], shape=(10000, 14))

In [25]:
from sklearn.model_selection import train_test_split

In [28]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [27]:
from sklearn.linear_model import LinearRegression
l=LinearRegression()

In [29]:
l.fit(X_train,Y_train)

LinearRegression()

In [30]:
y_predict=l.predict(X_test)

In [31]:
y_predict

array([ 2.47537227, -0.40879498,  1.95452049, ...,  2.99200788,
       -0.48307469,  1.84306253], shape=(2000,))

In [32]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(Y_test,y_predict)

0.6567341352913334

In [33]:
from sklearn.metrics import root_mean_squared_error
root_mean_squared_error(Y_test,y_predict)

0.8544871916588547

In [39]:
from sklearn.linear_model import Ridge
r=Ridge(alpha=0.01)

In [40]:
r.fit(X_train,Y_train)

Ridge(alpha=0.01)

In [41]:
y_predict=r.predict(X_test)

In [42]:
mean_absolute_error(Y_test,y_predict)

0.6567341014540539

In [43]:
root_mean_squared_error(Y_test,y_predict)

0.8544871929154424

In [ ]:
from sklearn.linear_model import Lasso
l=Lasso(alpha=0.01)

In [45]:
l.fit(X_train,Y_train)

LinearRegression()

In [46]:
y_predict=l.predict(X_test)

In [47]:
mean_absolute_error(Y_test,y_predict)

0.6567341352913334

In [48]:
root_mean_squared_error(Y_test,y_predict)

0.8544871916588547

In [49]:
from sklearn.linear_model import ElasticNet
e=ElasticNet()

In [50]:
l.fit(X_train,Y_train)

LinearRegression()

In [51]:
y_predict=l.predict(X_test)

In [52]:
mean_absolute_error(Y_test,y_predict)

0.6567341352913334

In [53]:
root_mean_squared_error(Y_test,y_predict)

0.8544871916588547

In [56]:
from sklearn.tree import DecisionTreeRegressor
tree=DecisionTreeRegressor(max_depth=5)

In [58]:
tree.fit(X_train,Y_train)

DecisionTreeRegressor(max_depth=5)

In [59]:
y_predict=tree.predict(X_test)

In [60]:
mean_absolute_error(Y_test,y_predict)

0.3697127695131148

In [61]:
root_mean_squared_error(Y_test,y_predict)

0.5893499585755801

In [62]:
from sklearn.ensemble import RandomForestRegressor
forest=RandomForestRegressor(n_estimators=100)

In [63]:
forest.fit(X_train,Y_train)

RandomForestRegressor()

In [64]:
y_predict=forest.predict(X_test)

In [65]:
mean_absolute_error(Y_test,y_predict)

0.38758499999999996

In [66]:
root_mean_squared_error(Y_test,y_predict)

0.5922182452440992

In [70]:
from sklearn.neighbors import KNeighborsRegressor
KNN=KNeighborsRegressor(n_neighbors=5)

In [71]:
KNN.fit(X_train,Y_train)

KNeighborsRegressor()

In [72]:
y_predict=KNN.predict(X_test)

In [73]:
mean_absolute_error(Y_test,y_predict)

0.45139999999999997

In [74]:
root_mean_squared_error(Y_test,y_predict)

0.6950683419635799

In [75]:
from sklearn.svm import SVR
svr=SVR(kernel='rbf')

In [77]:
svr.fit(X_train,Y_train)

SVR()

In [78]:
y_predict=svr.predict(X_test)

In [79]:
mean_absolute_error(Y_test,y_predict)

0.39158589566002894

In [80]:
root_mean_squared_error(Y_test,y_predict)

0.6197231676227142

In [81]:
from sklearn.ensemble import BaggingRegressor
bag=BaggingRegressor(n_estimators=100)

In [82]:
bag.fit(X_train,Y_train)

BaggingRegressor(n_estimators=100)

In [86]:
y_predict= bag.predict(X_test)

In [87]:
mean_absolute_error(Y_test,y_predict)

0.388065

In [88]:
root_mean_squared_error(Y_test,y_predict)

0.5930818240344244

In [89]:
from sklearn.ensemble import StackingRegressor  
from sklearn.ensemble import BaggingRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor

In [90]:
estimaters=[('rf',RandomForestRegressor()),('br',BaggingRegressor())]

In [91]:
stack=StackingRegressor(estimators=estimaters,final_estimator=DecisionTreeRegressor())

In [92]:
stack.fit(X_train,Y_train)

StackingRegressor(estimators=[('rf', RandomForestRegressor()),
                              ('br', BaggingRegressor())],
                  final_estimator=DecisionTreeRegressor())

In [93]:
y_predict=stack.predict(X_test)

In [94]:
mean_absolute_error(Y_test,y_predict)

0.45792346926078736

In [95]:
root_mean_squared_error(Y_test,y_predict)

0.7627723301595698

In [96]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor

In [98]:
param_grid = {
    'max_depth': [3, 5, 7, 10, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}


grid = GridSearchCV(DecisionTreeRegressor(), param_grid, cv=5)

In [99]:
grid.fit(X_train,Y_train)

GridSearchCV(cv=5, estimator=DecisionTreeRegressor(),
             param_grid={'max_depth': [3, 5, 7, 10, None],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10]})

In [100]:
print(grid.best_params_)
print(grid.best_score_)

{'max_depth': 5, 'min_samples_leaf': 4, 'min_samples_split': 2}
0.7894585602248508

In [101]:
from sklearn.tree import DecisionTreeRegressor
model=DecisionTreeRegressor(max_depth=5,min_samples_leaf=4,min_samples_split=2)

In [102]:
model.fit(X_train,Y_train)

DecisionTreeRegressor(max_depth=5, min_samples_leaf=4)

In [103]:
y_predict=model.predict(X_test)

In [104]:
mean_absolute_error(Y_test,y_predict)

0.3697127695131148

In [105]:
root_mean_squared_error(Y_test,y_predict)

0.5893499585755801

In [109]:
import pickle

with open('model.pkl', 'wb') as file:
    pickle.dump(model, file)

In [112]:
with open('model.pkl', 'rb') as file:
    new_model = pickle.load(file)

In [114]:
new_data = [[
    101,
    20,
    1,
    2,
    3,
    85,
    5,
    2,
    7,
    1,
    8.2,
    3,
    1,
    2
]]

prediction = model.predict(new_data)
print(prediction)

[1.70398482]