# feature encoding 
#### Feature encoding is the process of converting data (especially categorical or text data) into a numerical format that machine learning algorithms can understand.

## ordinal data-->
### Ordinal data is a type of categorical data where the categories have a meaningful order or ranking, but the difference between the categories is not necessarily equal.

## EX:
| Size        | Order |
| ----------- | ----- |
| Small       | 1st   |
| Medium      | 2nd   |
| Large       | 3rd   |
| Extra Large | 4th   |

# Nominal data --->
## it is a type of categorical data where the categories have no natural order or ranking

## ex:

| Color  |
| ------ |
| Red    |
| Blue   |
| Green  |
| Yellow |

# label enoder -->

### Label Encoding is a feature encoding technique that converts categorical values into integer labels

- ###  used when the output Col is in categorical formate

# Note:

### nominal data ---> one hot encoder is used
### ordinal data ---> ordinal encoder is used

In [1]:
import pandas as pd

In [3]:
bank=pd.read_csv('Bank_Marketing_Original_Data.csv')

In [4]:
bank

,Age,Job,Marital,Education,Default,Balance,Housing,Loan,contact,Day,Month,Duration,Campaign,Pdays,Previous,poutcome,TARGET
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,unknown,yes
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,unknown,yes
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success,yes
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,unknown,no
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other,no

In [5]:
bank['Education'].value_counts()

Education
secondary    23202
tertiary     13301
primary       6851
unknown       1857
Name: count, dtype: int64

In [ ]:
# tertiary> secondary > primary > unknown ---> this is ordinal data

# ordinal col--> education --> go with ordinal indocoder
# label encoder --> Target --> label label incoder
# nominal col ---> rest of other are nominal col

# lets perfrom them

### your input data must be in 2D formate

In [6]:
ordinal_data=bank[['Education']]

In [9]:
ordinal_data

       Education
0       tertiary
1      secondary
2      secondary
3        unknown
4        unknown
...          ...
45206   tertiary
45207    primary
45208  secondary
45209  secondary
45210  secondary

[45211 rows x 1 columns]

In [8]:
target_data=bank[['TARGET']]

In [10]:
target_data

      TARGET
0         no
1         no
2         no
3         no
4         no
...      ...
45206    yes
45207    yes
45208    yes
45209     no
45210     no

[45211 rows x 1 columns]

#### how i will go such type of encoding where tersery>secondary>primary>unknown
- ##### we will use the odinal encoder ---> the values which should be the hightest value will be written at the last 

- #### #### ordinalEncoder(categories=[['primary','secondary','tercery']])

In [11]:
from sklearn.preprocessing import OrdinalEncoder

In [15]:
oe=OrdinalEncoder(categories=[['unknown','primary','secondary','tertiary']])

In [16]:
ordinal_data=oe.fit_transform(ordinal_data)

In [17]:
ordinal_data

array([[3.],
       [2.],
       [2.],
       ...,
       [2.],
       [2.],
       [2.]], shape=(45211, 1))

In [18]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [20]:
target_data=le.fit_transform(target_data)

d:\genai\Machine learning\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [21]:
target_data

array([0, 0, 0, ..., 1, 0, 0], shape=(45211,))

---

# onehot encoder ---> use to convert the nominal data(text data) into the numerical data

# how the oneHotencoder is able to convert into the numerical data

| Color | Label |
| ----- | ----: |
| Red   |     0 |
| Blue  |     1 |
| Green |     2 |

### we can't compare the color with eachother that red>yellow>green  we can't compare ---> that's why it is nominal data --> onehotEncoder is used in this situation

| Original Color | Red | Blue | Green |
| -------------- | --: | ---: | ----: |
| Red            |   1 |    0 |     0 |
| Blue           |   0 |    1 |     0 |
| Green          |   0 |    0 |     1 |

#### in the table the sum will come out to be one --> that's why it is called oneHotEncoder

### as per the total number of categories ---> we have total number of col 

#### if colour is three --> then there will be three col

- ### sum of all columns is --> 1
#### that show some kind of dependency among these multiple columns

#### the input col --> need to have the independent col ---> but we see in the table that there is some dependency that the sum should be equal to one --> so we don't want from my side

# to remove the independency we have to do something --> this dependency is also called as multicollinearity ----> instead of going with the these 3 col vector ---> we will go with --> no of categories

# instead of going with the columns = number of categories ---> we will do this simple thing from my side that 
- ### col= [no of categoreis -1]

| Original Color | Red | Blue | Green |
| -------------- | --: | ---: | ----: |
| Red            |   1 |    0 |     0 | 
| Blue           |   0 |    1 |     0 |
| Green          |   0 |    0 |     1 |


#### red=[1,0,0]
#### blue=[0,1,0]
#### green=[0,0,1]

# what we will do to remove the multicolinearity--->
#### remove one col

#### red=[1,0,0]
#### blue=[0,1,0]
#### green=[0,0,1]

# what we will reduce --->
#### red=[1,0]
#### blue=[0,1]
#### green=[0,0]

# right now we only have 3 categories with us But what if ---> what if we have total number of categories 40 or 50
### we can take the example of ---> car price among ---> 40 countries of different brand --> so do we really feel that these 40 different oneHotEncoder ---> we will not go with this approch 

### so what we can do ?

#### suppose the maruti is ---> being reperted as max number of time 
#### BMW ---> is also repeted
####  and rest of 35 brand is not being repeated 

#### what can i do ---> 5 most repeated =5 different categories
#### rest of ----> other 

#### ---> this can be the approch from our side

-------------
----------

In [22]:
bank.head()

,Age,Job,Marital,Education,Default,Balance,Housing,Loan,contact,Day,Month,Duration,Campaign,Pdays,Previous,poutcome,TARGET
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [27]:
# first we will segrigate all the nominal col
nominal_data=bank[['Job', 'Marital', 'Default',  'Housing',
       'Loan', 'contact', 'Month','poutcome']]

In [28]:
nominal_data

                Job   Marital Default Housing Loan    contact Month poutcome
0        management   married      no     yes   no    unknown   may  unknown
1        technician    single      no     yes   no    unknown   may  unknown
2      entrepreneur   married      no     yes  yes    unknown   may  unknown
3       blue-collar   married      no     yes   no    unknown   may  unknown
4           unknown    single      no      no   no    unknown   may  unknown
...             ...       ...     ...     ...  ...        ...   ...      ...
45206    technician   married      no      no   no   cellular   nov  unknown
45207       retired  divorced      no      no   no   cellular   nov  unknown
45208       retired   married      no      no   no   cellular   nov  success
45209   blue-collar   married      no      no   no  telephone   nov  unknown
45210  entrepreneur   married      no      no   no   cellular   nov    other

[45211 rows x 8 columns]

In [29]:
bank['Marital'].value_counts()

Marital
married     27214
single      12790
divorced     5207
Name: count, dtype: int64

In [32]:
from sklearn.preprocessing import OneHotEncoder

In [34]:
ohe=OneHotEncoder()

In [36]:
nominal_data=ohe.fit_transform(nominal_data)

In [37]:
nominal_data

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 361688 stored elements and shape (45211, 40)>

# ---> we can say this is not the good approch that first we are seperating the nominal col ---> column tansformer will be the better approch there