# Langchain  ====> to build Ai application by chaining multiple LLMs

# langGraph ----> graph we will get in multipal LLMs --> use in complex model

### made up of two things
- lang ---> Language model -->LLM(Large Language Model)
- chain -->Chain

# suppose we want data summerization
### we do to chatgpt for it --> but chatgpt is not good at data summerization 
### perplexity is good at data summerization like task

## but chatgpt+perplexity ---> both combine will give the most optimal data summarization =====> there we are chaining multipal LLM models Togeather

# langchain and langgraph --> by using both we can make ai application

- langchain --> use to  make the basic ai application 
- langgraph --> can make complex ai applicaiton --> ex: AI agent

-----

# automated data cleaning

### for automated data cleaning we go with the --->(simple imputer) --> automated data cleaning --> it is funciton in the sklearn

## now we have to understand that what type of simple imputer we should use in every condition we can't go with the simple inputer

# we have three type of data cleaing based on what the pattern in the missing values as per that we will go to the data cleaning process

# there are 3 different pattern 
- ## Missing completly at random --> NO PATTERN is for missing data ---> ways are to fill the data --> fillna,dropna,ffill,bfill



- ## Missing at random ---> there is pattern in the missing data with the column values --> with the help of corresponding col only we will fill the data  --> can use --> Knn,other  col to fill


- ## Missing not at Random --> there is no pattern  --> need the domain expert there

# Missing completly at random ---> lets understand this with examples

#### suppose we have the patient data --> Nurse is filling this data ---> suppose we have 10000 patients --> means we have manuall data filling process 

#### supppose in some situation the nurse is not able to fill the (Weight values) for the specific patients or we can say for name also ---> nurse might would have skipped the values 


#### ----> By this we can understand that there is no pattern in missing data

### we can also take the another example --> e-commerce data

#### user's country --> data entry --> some values got currupted due to system gliche ---> there is not patten in it

# Missing at random ---> lets understand this

## we can take the example of healthcare --> weight is missing --> but we can find the pattern in it --> ex: femal weight is missing 
## --> pattern is comming between weight value and gender

# Missing not at Random --> lets understand this 
### suppose we have the data of 1000 user --> have salary data ---> came up with that some of the user are hiding or their income value is actully missing  ---> resons can be (high earner)--> not filling their total monthly income --> they don't want to pay the tax 

## there is not pattern with corresponding to any other col --> we can't figure with the other col that why the data is empty 

## there is a deliberate or known reasons why the data is missing

--------
-------

# Automated Data Cleaning

In [142]:
import pandas as pd

In [143]:
df=pd.read_csv('unclean_smartwatch_health_data.csv')

In [144]:
df.head()

,User ID,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
0,4174.0,58.939776,98.809650,5450.390578,7.167235622316564,Highly Active,1
1,NaN,NaN,98.532195,727.601610,6.538239375570314,Highly_Active,5
2,1860.0,247.803052,97.052954,2826.521994,ERROR,Highly Active,5
3,2294.0,40.000000,96.894213,13797.338044,7.367789630207228,Actve,3
4,2130.0,61.950165,98.583797,15679.067648,NaN,Highly_Active,6

In [145]:
df.isnull().sum()

User ID                   201
Heart Rate (BPM)          400
Blood Oxygen Level (%)    300
Step Count                100
Sleep Duration (hours)    150
Activity Level            200
Stress Level              200
dtype: int64

# we have to identify how the data is missing

## we can see that user id is unnessory for us so we will drop it

In [146]:
df=df.drop(columns='User ID')

In [147]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        9600 non-null   float64
 1   Blood Oxygen Level (%)  9700 non-null   float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(3), str(3)
memory usage: 468.9 KB

In [148]:
df['Heart Rate (BPM)'].isnull().sum()

np.int64(400)

# now we which check that heart rate is in which calagory bro

In [149]:
df[df['Heart Rate (BPM)'].isnull()==True]

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
1,NaN,98.532195,727.601610,6.538239375570314,Highly_Active,5
17,NaN,96.052853,3488.919508,6.718661172525927,Seddentary,4
75,NaN,100.000000,3124.118038,4.229887888280923,Actve,1
105,NaN,98.276558,3039.112276,5.209658021888749,NaN,6
158,NaN,99.478461,11559.663606,6.470651489160172,Highly_Active,7
...,...,...,...,...,...,...
9875,NaN,99.842527,4454.770218,5.520745925308887,Sedentary,3
9956,NaN,100.000000,3584.236177,6.659533807452561,Highly_Active,5
9971,NaN,99.319841,26.215769,6.367659085134144,Active,10
9990,NaN,100.000000,3817.269018,8.595259517189332,Seddentary,2
9998,NaN,98.401058,3364.788855,5.691233932149209,Active,8

In [150]:
# first way --> dropna()

In [151]:
# second way --> replace with mean mode or median to the missing data

In [152]:
# while going for mean ----> always and always check for outliers 
# ex : age=500 --> we have to remove it if we want to replace it with mean()

# median()---> if you will arange all values from assending then it will replace with middle value 

# mode() ---> most frequest value

In [153]:
df['Heart Rate (BPM)'].describe()

count    9600.000000
mean       76.035462
std        19.412483
min        40.000000
25%        64.890152
50%        75.220601
75%        85.198249
max       296.593970
Name: Heart Rate (BPM), dtype: float64

In [154]:
df['Heart Rate (BPM)'].median()

np.float64(75.22060125775644)

In [155]:
df['Heart Rate (BPM)'].mean()

np.float64(76.03546175646017)

In [156]:
df['Heart Rate (BPM)']=df['Heart Rate (BPM)'].fillna(df['Heart Rate (BPM)'].mean())

In [157]:
df['Heart Rate (BPM)'].isnull().sum()

np.int64(0)

In [158]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  9700 non-null   float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(3), str(3)
memory usage: 468.9 KB

In [159]:
df['Blood Oxygen Level (%)'].isnull().sum()

np.int64(300)

In [160]:
df[df['Blood Oxygen Level (%)'].isnull()==True]

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
10,101.914938,NaN,2987.568640,7.541956463173237,Sedentary,9
21,68.310104,NaN,1058.374274,6.456918401449286,Actve,3
133,77.907578,NaN,15672.467752,9.079469571860296,Sedentary,10
134,78.227923,NaN,789.365922,3.5252990125882064,Seddentary,3
187,89.486636,NaN,2689.849911,5.737108446097524,Seddentary,6
...,...,...,...,...,...,...
9834,64.803112,NaN,1647.308449,8.04238137746177,Highly Active,7
9861,57.617790,NaN,14269.737149,6.390686112594759,Highly_Active,9
9885,75.281591,NaN,3852.160740,8.970316986352344,Actve,NaN
9905,87.693723,NaN,2364.028205,3.5490963940132865,Seddentary,3
9979,58.797407,NaN,359.210435,8.035879532058063,Active,5

In [161]:
df.describe()

       Heart Rate (BPM)  Blood Oxygen Level (%)    Step Count
count      10000.000000             9700.000000   9900.000000
mean          76.035462               97.841581   6985.685885
std           19.020232                1.732863   6885.809680
min           40.000000               90.791208      0.910138
25%           65.322796               96.662683   2021.039657
50%           76.035462               98.010642   4962.534599
75%           84.791711               99.376179   9724.902880
max          296.593970              100.000000  62486.690753

In [162]:
df['Blood Oxygen Level (%)']=df['Blood Oxygen Level (%)'].fillna(df['Blood Oxygen Level (%)'].mean())

In [163]:
df.isnull().sum()

Heart Rate (BPM)            0
Blood Oxygen Level (%)      0
Step Count                100
Sleep Duration (hours)    150
Activity Level            200
Stress Level              200
dtype: int64

# forword filling and bacword filling --> on time series data

## forword filling --> 
#### 5
#### 6
#### 7
#### 7---> filling na_values the values which is last valid value
#### 8
#### 9
#### 10


## backword filling -->
#### 5
#### 6
#### 7
#### 7---> filling the na_value with the next valid value
#### 8
#### 9
#### 10

In [164]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(3), str(3)
memory usage: 468.9 KB

In [165]:
df[df['Step Count'].isnull()==True]

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
136,70.593014,97.473981,NaN,3.439287691081752,Highly_Active,6
204,76.035462,98.710637,NaN,5.756958709255954,Highly_Active,8
603,69.084103,99.627473,NaN,6.358184719715759,Highly_Active,7
716,83.258294,98.704757,NaN,5.486240700986009,Seddentary,3
739,97.506420,97.651407,NaN,7.465981460156365,Active,6
...,...,...,...,...,...,...
9097,62.072133,96.810967,NaN,5.828570383973958,Seddentary,6
9121,54.793814,99.670176,NaN,6.686430627866978,Seddentary,2
9191,101.777396,100.000000,NaN,8.07989468005159,Active,10
9527,76.035462,94.694312,NaN,4.186856483292383,Seddentary,4
9565,90.411615,95.009355,NaN,8.582820460042822,Sedentary,4

### we will use the -->  --> to use the ffill() or bfill()

In [166]:
df['Step Count'] = df['Step Count'].ffill()

In [167]:
df.isnull().sum()

Heart Rate (BPM)            0
Blood Oxygen Level (%)      0
Step Count                  0
Sleep Duration (hours)    150
Activity Level            200
Stress Level              200
dtype: int64

In [168]:
df['Sleep Duration (hours)'].isnull().sum()

np.int64(150)

In [169]:
df[df['Sleep Duration (hours)']=='ERROR']

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
2,247.803052,97.052954,2826.521994,ERROR,Highly Active,5
62,115.078288,99.928041,1918.372142,ERROR,Highly_Active,4
71,64.799778,94.743857,4613.859266,ERROR,Highly_Active,10
81,41.709895,96.857347,1413.015778,ERROR,Highly_Active,4
92,70.243810,97.171134,2336.583406,ERROR,Highly Active,7
...,...,...,...,...,...,...
9901,63.369107,96.229029,6656.786482,ERROR,Active,4
9912,75.933666,97.386073,1813.072248,ERROR,Sedentary,10
9927,87.579045,98.768633,3727.161872,ERROR,Active,1
9943,91.834863,96.145378,38831.465057,ERROR,Active,4
9951,70.335328,98.560133,1997.442874,ERROR,Highly_Active,9

In [170]:
# we will convert the error values into missing values

# we have to convert the object data type to numeric type --> to_numeric()

In [171]:
# this will convert the ERROR values into the NaN values

df['Sleep Duration (hours)']=pd.to_numeric(df['Sleep Duration (hours)'],errors='coerce')

In [172]:
df['Sleep Duration (hours)'].isnull().sum()

np.int64(397)

In [173]:
df['Sleep Duration (hours)'].dtype

dtype('float64')

In [174]:
df['Sleep Duration (hours)'].mean()

np.float64(6.505462918406444)

In [175]:
df['Sleep Duration (hours)'].median()

np.float64(6.503308362112644)

In [176]:
df['Sleep Duration (hours)']=df['Sleep Duration (hours)'].fillna(df['Sleep Duration (hours)'].mean())

In [177]:
df['Sleep Duration (hours)'].isnull().sum()

np.int64(0)

# how we can fill the categorical values now bro yoooo--->

## for categorical values we can go with ---> mode()---> values with most frequency in our col

In [178]:
df['Activity Level'].mode()

0    Seddentary
Name: Activity Level, dtype: str

In [179]:
df['Activity Level'].isnull().sum()

np.int64(200)

In [180]:
df['Activity Level']=df['Activity Level'].fillna(df['Activity Level'].mode())

In [181]:
df.isnull().sum()

Heart Rate (BPM)            0
Blood Oxygen Level (%)      0
Step Count                  0
Sleep Duration (hours)      0
Activity Level            200
Stress Level              200
dtype: int64

In [182]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              10000 non-null  float64
 3   Sleep Duration (hours)  10000 non-null  float64
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(4), str(2)
memory usage: 468.9 KB

# constent imputation --> when you want to fill missing value with a constent value like --> 'unknown',-999,0

In [183]:
df['Stress Level'].value_counts()

Stress Level
2            1007
7            1006
6            1001
3             995
1             984
9             976
4             966
10            954
5             945
8             917
Very High      49
Name: count, dtype: int64

In [184]:
df['Stress Level']=df['Stress Level'].fillna(5)

In [185]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              10000 non-null  float64
 3   Sleep Duration (hours)  10000 non-null  float64
 4   Activity Level          9800 non-null   str
 5   Stress Level            10000 non-null  object
dtypes: float64(4), object(1), str(1)
memory usage: 468.9+ KB

# different imputation techniques

### 1.remove the missing values
### 2.mean or median impution --> goes for numeric col
### 3.mode imputation --> goes for categorical col
### 4.constent or sentinel value imputation
### 5.forword fill or backword fill --> use in time series dataset
#
### 6.Simple Imputer ---> from Scikit learn 
- #### it is going to take the input as 2D vector   --> one col ---> impution --> 2D col  or 2D array ---> we have to convert the 2D array into 1D array by ravel() ---> simple imputer will ask out for the parameter ---> strategy ---> this decides what imputation you can go with 
- strategy --> can be mean ,median,most_frequent

In [186]:
df=pd.read_csv('unclean_smartwatch_health_data.csv')

In [187]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   User ID                 9799 non-null   float64
 1   Heart Rate (BPM)        9600 non-null   float64
 2   Blood Oxygen Level (%)  9700 non-null   float64
 3   Step Count              9900 non-null   float64
 4   Sleep Duration (hours)  9850 non-null   str
 5   Activity Level          9800 non-null   str
 6   Stress Level            9800 non-null   str
dtypes: float64(4), str(3)
memory usage: 547.0 KB

In [188]:
df=df.drop(columns='User ID')

In [189]:
df.head()

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
0,58.939776,98.809650,5450.390578,7.167235622316564,Highly Active,1
1,NaN,98.532195,727.601610,6.538239375570314,Highly_Active,5
2,247.803052,97.052954,2826.521994,ERROR,Highly Active,5
3,40.000000,96.894213,13797.338044,7.367789630207228,Actve,3
4,61.950165,98.583797,15679.067648,NaN,Highly_Active,6

In [190]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(strategy='median')

In [191]:
df['Heart Rate (BPM)']=imputer.fit_transform(df[['Heart Rate (BPM)']]).ravel()

# we have to convert it into the 2D

In [192]:
df['Heart Rate (BPM)']=imputer.fit_transform(df[['Heart Rate (BPM)']]).ravel()

In [193]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  9700 non-null   float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(3), str(3)
memory usage: 468.9 KB

In [194]:
df['Blood Oxygen Level (%)'].describe()

count    9700.000000
mean       97.841581
std         1.732863
min        90.791208
25%        96.662683
50%        98.010642
75%        99.376179
max       100.000000
Name: Blood Oxygen Level (%), dtype: float64

In [195]:
imputer=SimpleImputer(strategy='mean')

In [196]:
df['Blood Oxygen Level (%)']=imputer.fit_transform(df[['Blood Oxygen Level (%)']]).ravel()

In [197]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(3), str(3)
memory usage: 468.9 KB

In [198]:
imputer=SimpleImputer(strategy='most_frequent')

In [199]:
df['Activity Level']=imputer.fit_transform(df[['Activity Level']]).ravel()

In [200]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          10000 non-null  str
 5   Stress Level            9800 non-null   str
dtypes: float64(3), str(3)
memory usage: 468.9 KB

In [201]:
imputer=SimpleImputer(strategy='constant',fill_value=5)
df['Stress Level']=imputer.fit_transform(df[['Stress Level']]).ravel()

In [202]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          10000 non-null  str
 5   Stress Level            10000 non-null  object
dtypes: float64(3), object(1), str(2)
memory usage: 468.9+ KB