# data geathering using read_csv('') --> csv files

## 1. how to read the content from the csv file

In [ ]:
import pandas as pd

In [37]:
pd.read_csv('Titanic.csv')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

# csv file ---> comma seperated values --> ex: rajveer,21,kct
# tsv file ---> tab seperaed values  ---> ex: rajveer   21  kct

# how can we read the tsv file

### we have parameter here ---> sep

## read_csv() --> sep (seperation) --> how values are seperated from each other in the given file

#### csv --> amit,28 --> sep=","
#### tsv --> amit\t28 --> sep="\t"

In [38]:
df = pd.read_csv(
    r"D:\genai\Machine learning\data geathering\test_Arabic_tweets_negative_20190413.tsv",
    sep="\t"
)

In [39]:
df

      neg              حتى الايتونز خربتوه مو صاحين انتو؟؟ 😭
0     neg  واحد تبع النظام السوري يقول أن المخابرات السور...
1     neg  الى متى التعامل السئ للخادمات وعدم احترامهم وك...
2     neg                  رايح جاي ي طحلبي 🐸 #الهلال_الاهلي
3     neg                                 تتمغط ومعها سداع 😫
4     neg  اذا ما كان ألطف كوبل مر عليكم 😭😭💛💛 حظ جانيت بس...
...   ...                                                ...
5762  neg  النوم وانت مكسور ده احساس غبي اللي هو مش قادر ...
5763  neg  استشهاد_الامام_كاظم_الغيظ السلام على المعذب في...
5764  neg                          انا كنت اكل الصحن بكبره 😐
5765  neg  قولوا لي ايش تشوفوا .. مع ملاحظة التلطف لأنه ا...
5766  neg  ✍ إذا أردت أن تعرف شيئا عني إسالني قبل أن تسأل...

[5767 rows x 2 columns]

# if you want to provide personal name to the col instead to the col name that are in the dataset the you can use

# name=['name1','name2','name3']

In [40]:
pd.read_csv('Titanic.csv',names=['pid','Survived','Pclass','P_Name','Gender','Age','Sibling or Spouse','Parch','Ticket_id','Fare','Cabin','Starting Journey'])

,pid,Survived,Pclass,P_Name,Gender,Age,Sibling or Spouse,Parch,Ticket_id,Fare,Cabin,Starting Journey
0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
2,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47,1,0,363272,7,NaN,S
3,894,0,2,"Myles, Mr. Thomas Francis",male,62,0,0,240276,9.6875,NaN,Q
4,895,0,3,"Wirz, Mr. Albert",male,27,0,0,315154,8.6625,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
414,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.05,NaN,S
415,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39,0,0,PC 17758,108.9,C105,C
416,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.25,NaN,S
417,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.05,NaN,S
418,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

# what we can see that our previous col name is comming out to be the row now so what we can do

# header -->header parmeter make sure that the any of the row name will be shown as the col name only based on the indexing of rows

In [41]:
pd.read_csv('Titanic.csv',header=1)

,892,0,3,"Kelly, Mr. James",male,34.5,0.1,0.2,330911,7.8292,Unnamed: 10,Q
0,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
1,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
2,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
3,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
4,897,0,3,"Svensson, Mr. Johan Cervin",male,14.0,0,0,7538,9.2250,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
412,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
413,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
414,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
415,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
416,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [42]:
pd.read_csv('Titanic.csv')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

# index_col--> keep one of the col as index

In [43]:
pd.read_csv('Titanic.csv',index_col='PassengerId')

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

# usecols--> what col we should use to show out of all of the col we are having in the dataframe --> use the list to meantion all the name of the col names which are required

In [44]:
pd.read_csv('Student Depression Dataset.csv',usecols=['id','Gender','Age'])

           id  Gender   Age
0           2    Male  33.0
1           8  Female  24.0
2          26    Male  31.0
3          30  Female  28.0
4          32  Female  25.0
...       ...     ...   ...
27896  140685  Female  27.0
27897  140686    Male  27.0
27898  140689    Male  31.0
27899  140690  Female  18.0
27900  140699    Male  27.0

[27901 rows x 3 columns]

# squeeze --> DataFrame --> Series --> squeeze --> True --> combination of usecol and squeeze -->True

In [45]:
pd.read_csv('Titanic.csv',usecols=['Survived']).squeeze()

0      0
1      1
2      0
3      0
4      1
      ..
413    0
414    1
415    0
416    0
417    0
Name: Survived, Length: 418, dtype: int64

# nrows--> it is going to help us with a fixed no of rows out of the complete data we have

In [46]:
pd.read_csv('Student Depression Dataset.csv',nrows=1000)

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,5128,Male,30.0,Srinagar,Student,4.0,0.0,6.99,4.0,0.0,More than 8 hours,Unhealthy,B.Tech,Yes,0.0,3.0,Yes,0
996,5130,Female,28.0,Kalyan,Student,3.0,0.0,9.60,4.0,0.0,Less than 5 hours,Moderate,B.Tech,Yes,2.0,5.0,Yes,1
997,5136,Male,28.0,Surat,Student,4.0,0.0,5.74,3.0,0.0,More than 8 hours,Unhealthy,M.Pharm,No,6.0,1.0,Yes,0
998,5142,Female,31.0,Delhi,Student,3.0,0.0,8.93,2.0,0.0,Less than 5 hours,Healthy,LLM,No,12.0,1.0,No,0
999,5144,Male,29.0,Delhi,Student,4.0,0.0,7.64,4.0,0.0,7-8 hours,Unhealthy,Class 12,Yes,7.0,4.0,Yes,1

# encoding issue --> when ever we are working on the numerical kind of col then its incoding is done in --> utf-8

# sometime we have a data which has emoji like thing then we will face the issue in encoding with utf-8---> so we have to manully keep the encoing --> utf-8 ---> read the content from the dataset --> we will use the incoding parameter

## encoding --> it make sure that the data is in the--> utf-8 formate only --> encoding='latin-1'

In [47]:
pd.read_csv('Titanic.csv',encoding='latin-1')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

# suppose you have the dataset and one one row there are 5 values and in another row there are 6 values so it will create an issue --> there should be equal number of col in each row so we have to remove these 

take another example we have 6000 lines of data and 5500 line have 6 values and rest of them have 5 values so we have to remove the rest of line which have 5 values only ans these are known as error bad line

# we have a parmeter to solve these type of thing

# on_bad_lines --> we can have some rows with 8 valeus while other will have 9 values so these row with 8 values should be romoved --> error_bad_lines=False

In [52]:
pd.read_csv('Titanic.csv', on_bad_lines='skip')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

# dtype--> it can assign initially only with a specific data type to a col
### syntex --> dtype={'col_1':int,'col_2'=float}

In [53]:
pd.read_csv('Student Depression Dataset.csv',dtype={'Age':int})

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [55]:
df=pd.read_csv('Chocolate Sales (2).csv')

In [56]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3282 entries, 0 to 3281
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sales Person   3282 non-null   str
 1   Country        3282 non-null   str
 2   Product        3282 non-null   str
 3   Date           3282 non-null   str
 4   Amount         3282 non-null   str
 5   Boxes Shipped  3282 non-null   int64
dtypes: int64(1), str(5)
memory usage: 154.0 KB

In [59]:
df=pd.read_csv('Chocolate Sales (2).csv',parse_dates=['Date'])

In [60]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3282 entries, 0 to 3281
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sales Person   3282 non-null   str
 1   Country        3282 non-null   str
 2   Product        3282 non-null   str
 3   Date           3282 non-null   str
 4   Amount         3282 non-null   str
 5   Boxes Shipped  3282 non-null   int64
dtypes: int64(1), str(5)
memory usage: 154.0 KB

# converter ---> bring the transform or change specific values in a col with another value & we use this function remember it is a function

In [61]:
# define a funcation

def station(value):
    if value=='Q':
        return 'Queenstown'
    else:
        return value

In [62]:
pd.read_csv('Titanic.csv',converters={'Embarked':station})

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Queenstown
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Queenstown
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

# na_values--> parameter

#### na_values can help us out with mentioning what values to be considered as an missing values

#### syntex:- na_values['/','NO',':']

In [64]:
pd.read_csv('Titanic.csv',na_values=['/','NO',':','NaN'])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

# loading huge dataset in chunks ---> parameter--> chunksize=num_value --> suppose we have 20000 line of data but i want 5000 in every dataframe --> chunksize=5000

In [66]:
dfs=pd.read_csv('Student Depression Dataset.csv',chunksize=5000)

In [67]:
dfs

In [68]:
for chunks in dfs:
    print(chunks.shape)

(5000, 18)
(5000, 18)
(5000, 18)
(5000, 18)
(5000, 18)
(2901, 18)