In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
df=pd.read_csv('heart_disease_cleaned.csv')

In [3]:
df.head()

,id,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
0,1,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,2,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,2
2,3,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,4,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,5,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0

In [4]:
df.shape

(919, 16)

In [5]:
def x(value):
    if value==0:
        return 'No'
    else:
        return 'Yes'

In [6]:
df['disease']=df['num'].apply(x)

In [7]:
df.head()

,id,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num,disease
0,1,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0,No
1,2,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,2,Yes
2,3,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1,Yes
3,4,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0,No
4,5,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0,No

In [8]:
df.drop(columns=['id','num'],inplace=True)

In [9]:
df.head()

,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,disease
0,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,No
1,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,Yes
2,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,Yes
3,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,No
4,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,No

In [10]:
numeric_data=['age','trestbps','chol','thalch','oldpeak','ca']
ordinal_data=['slope']
nominal_data=['sex','dataset','cp','fbs','restecg','exang','thal']

In [11]:
from sklearn.preprocessing import OneHotEncoder,StandardScaler,OrdinalEncoder,LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

In [12]:
df['slope'].unique()

<ArrowStringArray>
['downsloping', 'flat', 'upsloping']
Length: 3, dtype: str

In [13]:
numeric_pipeline=Pipeline(steps=[('impute',SimpleImputer(strategy='median')),('scaling',StandardScaler())])
ordina_pipeline=Pipeline(steps=[('impute',SimpleImputer(strategy='most_frequent')),('encodng',OrdinalEncoder(categories=[['downsloping', 'flat', 'upsloping']])),('scaling',StandardScaler())])
nominal_pipeline=Pipeline(steps=[('impute',SimpleImputer(strategy='most_frequent')),('encoding',OneHotEncoder(handle_unknown='ignore'))])

In [14]:
tranform=ColumnTransformer(transformers=[('numeric',numeric_pipeline,numeric_data),('nominal',nominal_pipeline,nominal_data),('ordinal',ordina_pipeline,ordinal_data)])

In [15]:
tranform

ColumnTransformer(transformers=[('numeric',
                                 Pipeline(steps=[('impute',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaling',
                                                  StandardScaler())]),
                                 ['age', 'trestbps', 'chol', 'thalch',
                                  'oldpeak', 'ca']),
                                ('nominal',
                                 Pipeline(steps=[('impute',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoding',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['sex', 'dataset', 'cp', 'fbs', 'restecg',
                                  'exang', 'thal']),
                                ('ordinal',
                                 Pipeline(steps=[('impute',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encodng',
                                                  OrdinalEncoder(categories=[['downsloping',
                                                                              'flat',
                                                                              'upsloping']])),
                                                 ('scaling',
                                                  StandardScaler())]),
                                 ['slope'])])

In [16]:
df.columns

Index(['age', 'sex', 'dataset', 'cp', 'trestbps', 'chol', 'fbs', 'restecg',
       'thalch', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'disease'],
      dtype='str')

In [17]:
X=df[['age', 'sex', 'dataset', 'cp', 'trestbps', 'chol', 'fbs', 'restecg',
       'thalch', 'exang', 'oldpeak', 'slope', 'ca', 'thal']]
Y=df['disease']

In [18]:
from sklearn.linear_model import LogisticRegression

In [19]:
model=Pipeline(steps=[('tranform',tranform),('algo',LogisticRegression())])

In [20]:
Y = Y.map({'No': 0, 'Yes': 1})

In [21]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [22]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [23]:
param_grid=[
 {'algo':[LogisticRegression(max_iter=1000)],
   'algo__C':[0.01,0.1,1,10]
 },

 {
     'algo':[DecisionTreeClassifier()],
     'algo__max_depth':[3,5,10,None],
     'algo__min_samples_split':[2,5,10]
 },

 {
     'algo':[RandomForestClassifier()],
     'algo__n_estimators':[100,200],
     'algo__max_depth': [5, 10, None]
 },

 {
     'algo':[SVC()],
     'algo__C':[0.1,1,10],
     'algo__kernel':['linear','rbf','poly']
 }



]

In [24]:
grid = GridSearchCV(
    estimator=model,
    param_grid=param_grid,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    error_score='raise'
)

grid.fit(X_train, Y_train)

GridSearchCV(cv=5, error_score='raise',
             estimator=Pipeline(steps=[('tranform',
                                        ColumnTransformer(transformers=[('numeric',
                                                                         Pipeline(steps=[('impute',
                                                                                          SimpleImputer(strategy='median')),
                                                                                         ('scaling',
                                                                                          StandardScaler())]),
                                                                         ['age',
                                                                          'trestbps',
                                                                          'chol',
                                                                          'thalch',
                                                                          'oldpeak',
                                                                          'ca']),
                                                                        ('nominal',
                                                                         Pipeline(steps=[('impute',
                                                                                          SimpleImputer(strategy='most_frequent')),
                                                                                         ('encoding'...
             param_grid=[{'algo': [LogisticRegression(max_iter=1000)],
                          'algo__C': [0.01, 0.1, 1, 10]},
                         {'algo': [DecisionTreeClassifier()],
                          'algo__max_depth': [3, 5, 10, None],
                          'algo__min_samples_split': [2, 5, 10]},
                         {'algo': [RandomForestClassifier()],
                          'algo__max_depth': [5, 10, None],
                          'algo__n_estimators': [100, 200]},
                         {'algo': [SVC()], 'algo__C': [0.1, 1, 10],
                          'algo__kernel': ['linear', 'rbf', 'poly']}],
             scoring='f1')

In [25]:
Y_predict=grid.predict(X_test)

In [26]:
from sklearn.metrics import accuracy_score

In [27]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,
    roc_auc_score
)





print("Accuracy  :", accuracy_score(Y_test, Y_predict))
print("Precision :", precision_score(Y_test, Y_predict))
print("Recall    :", recall_score(Y_test, Y_predict))
print("F1 Score  :", f1_score(Y_test, Y_predict))
print("ROC-AUC   :", roc_auc_score(Y_test, Y_predict))

Accuracy  : 0.8532608695652174
Precision : 0.91
Recall    : 0.8348623853211009
F1 Score  : 0.8708133971291866
ROC-AUC   : 0.8574311926605505

In [30]:
from xgboost import XGBClassifier

In [44]:
clf =Pipeline(steps=[('tranform',tranform),('model',XGBClassifier(
    n_estimators=100,       # how many trees
    learning_rate=1,      # how much each tree contributes (lower = need more trees)
    max_depth=3,            # how complex each tree is
    subsample=0.8,          # fraction of rows used per tree
    colsample_bytree=0.8,   # fraction of features used per tree
    random_state=42
))])

In [45]:
clf.fit(X_train,Y_train)

Pipeline(steps=[('tranform',
                 ColumnTransformer(transformers=[('numeric',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaling',
                                                                   StandardScaler())]),
                                                  ['age', 'trestbps', 'chol',
                                                   'thalch', 'oldpeak', 'ca']),
                                                 ('nominal',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoding',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['sex...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=1,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=3, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=100, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [46]:
from sklearn.metrics import accuracy_score

In [47]:
accuracy_score(Y_test,Y_predict)

0.8532608695652174

In [48]:

print("Accuracy  :", accuracy_score(Y_test, Y_predict))
print("Precision :", precision_score(Y_test, Y_predict))
print("Recall    :", recall_score(Y_test, Y_predict))
print("F1 Score  :", f1_score(Y_test, Y_predict))
print("ROC-AUC   :", roc_auc_score(Y_test, Y_predict))

Accuracy  : 0.8532608695652174
Precision : 0.91
Recall    : 0.8348623853211009
F1 Score  : 0.8708133971291866
ROC-AUC   : 0.8574311926605505