In [40]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [41]:
df=pd.read_csv('data.csv')

In [42]:
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [43]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           4600 non-null   str
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   float64
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64
 5   sqft_lot       4600 non-null   int64
 6   floors         4600 non-null   float64
 7   waterfront     4600 non-null   int64
 8   view           4600 non-null   int64
 9   condition      4600 non-null   int64
 10  sqft_above     4600 non-null   int64
 11  sqft_basement  4600 non-null   int64
 12  yr_built       4600 non-null   int64
 13  yr_renovated   4600 non-null   int64
 14  street         4600 non-null   str
 15  city           4600 non-null   str
 16  statezip       4600 non-null   str
 17  country        4600 non-null   str
dtypes: float64(4), int64(9), str(5)
memory usage: 893.1 KB

In [44]:
df['date']=pd.to_datetime(df['date'])

In [45]:
df['date'].dtypes

dtype('<M8[us]')

In [46]:
df['day']=df['date'].dt.day
df['month']=df['date'].dt.month
df['year']=df['date'].dt.year

In [47]:
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,...,sqft_basement,yr_built,yr_renovated,street,city,statezip,country,day,month,year
0,2014-05-02,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,...,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA,2,5,2014
1,2014-05-02,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,...,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA,2,5,2014
2,2014-05-02,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,...,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA,2,5,2014
3,2014-05-02,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,...,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA,2,5,2014
4,2014-05-02,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,...,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA,2,5,2014

In [48]:
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,...,sqft_basement,yr_built,yr_renovated,street,city,statezip,country,day,month,year
0,2014-05-02,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,...,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA,2,5,2014
1,2014-05-02,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,...,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA,2,5,2014
2,2014-05-02,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,...,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA,2,5,2014
3,2014-05-02,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,...,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA,2,5,2014
4,2014-05-02,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,...,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA,2,5,2014

In [49]:
df['statezip'].unique()

<ArrowStringArray>
['WA 98133', 'WA 98119', 'WA 98042', 'WA 98008', 'WA 98052', 'WA 98115',
 'WA 98038', 'WA 98045', 'WA 98155', 'WA 98105', 'WA 98074', 'WA 98106',
 'WA 98007', 'WA 98092', 'WA 98198', 'WA 98006', 'WA 98102', 'WA 98011',
 'WA 98125', 'WA 98003', 'WA 98136', 'WA 98033', 'WA 98029', 'WA 98117',
 'WA 98034', 'WA 98072', 'WA 98023', 'WA 98107', 'WA 98166', 'WA 98116',
 'WA 98024', 'WA 98055', 'WA 98077', 'WA 98027', 'WA 98059', 'WA 98075',
 'WA 98014', 'WA 98065', 'WA 98199', 'WA 98053', 'WA 98058', 'WA 98122',
 'WA 98103', 'WA 98112', 'WA 98005', 'WA 98118', 'WA 98177', 'WA 98004',
 'WA 98019', 'WA 98144', 'WA 98168', 'WA 98001', 'WA 98056', 'WA 98146',
 'WA 98028', 'WA 98148', 'WA 98057', 'WA 98040', 'WA 98010', 'WA 98051',
 'WA 98031', 'WA 98109', 'WA 98030', 'WA 98126', 'WA 98032', 'WA 98178',
 'WA 98288', 'WA 98108', 'WA 98070', 'WA 98188', 'WA 98002', 'WA 98039',
 'WA 98022', 'WA 98068', 'WA 98047', 'WA 98050', 'WA 98354']
Length: 77, dtype: str

In [50]:
df[['state','zip']]=df['statezip'].str.split(' ',expand=True)

In [51]:
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,...,yr_renovated,street,city,statezip,country,day,month,year,state,zip
0,2014-05-02,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,...,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA,2,5,2014,WA,98133
1,2014-05-02,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,...,0,709 W Blaine St,Seattle,WA 98119,USA,2,5,2014,WA,98119
2,2014-05-02,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,...,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA,2,5,2014,WA,98042
3,2014-05-02,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,...,0,857 170th Pl NE,Bellevue,WA 98008,USA,2,5,2014,WA,98008
4,2014-05-02,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,...,1992,9105 170th Ave NE,Redmond,WA 98052,USA,2,5,2014,WA,98052

In [52]:
df=df.drop(columns='statezip')

In [53]:
df=df.drop(columns='street')

In [54]:
df=df.drop(columns='date')

In [55]:
df.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,city,country,day,month,year,state,zip
0,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,Shoreline,USA,2,5,2014,WA,98133
1,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,Seattle,USA,2,5,2014,WA,98119
2,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,Kent,USA,2,5,2014,WA,98042
3,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,Bellevue,USA,2,5,2014,WA,98008
4,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,Redmond,USA,2,5,2014,WA,98052

In [56]:
df.columns

Index(['price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
       'waterfront', 'view', 'condition', 'sqft_above', 'sqft_basement',
       'yr_built', 'yr_renovated', 'city', 'country', 'day', 'month', 'year',
       'state', 'zip'],
      dtype='str')

In [57]:
numeric_data=[ 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
       'waterfront', 'view', 'condition', 'sqft_above', 'sqft_basement',
       'yr_built', 'yr_renovated', 'day', 'month', 'year',
        'zip']

In [58]:
categorical_data=['city','country','state']

In [59]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

In [60]:
numeric_pipeline=Pipeline(steps=[('impute',SimpleImputer(strategy='mean')),('scaling',StandardScaler())])
categorical_pipeline=Pipeline(steps=[('SimpleImputer',SimpleImputer(strategy='most_frequent')),('encoding',OneHotEncoder(handle_unknown='ignore'))])

In [61]:
from sklearn.compose import ColumnTransformer

In [62]:
feature = ColumnTransformer(transformers=[
    ('numeric', numeric_pipeline, numeric_data),
    ('categorical', categorical_pipeline, categorical_data)
])

In [63]:
feature

ColumnTransformer(transformers=[('numeric',
                                 Pipeline(steps=[('impute', SimpleImputer()),
                                                 ('scaling',
                                                  StandardScaler())]),
                                 ['bedrooms', 'bathrooms', 'sqft_living',
                                  'sqft_lot', 'floors', 'waterfront', 'view',
                                  'condition', 'sqft_above', 'sqft_basement',
                                  'yr_built', 'yr_renovated', 'day', 'month',
                                  'year', 'zip']),
                                ('categorical',
                                 Pipeline(steps=[('SimpleImputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoding',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['city', 'country', 'state'])])

In [64]:
from sklearn.linear_model import LinearRegression

In [65]:
model=Pipeline(steps=[('feature',feature),('regression',LinearRegression())])

In [66]:
model

Pipeline(steps=[('feature',
                 ColumnTransformer(transformers=[('numeric',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer()),
                                                                  ('scaling',
                                                                   StandardScaler())]),
                                                  ['bedrooms', 'bathrooms',
                                                   'sqft_living', 'sqft_lot',
                                                   'floors', 'waterfront',
                                                   'view', 'condition',
                                                   'sqft_above',
                                                   'sqft_basement', 'yr_built',
                                                   'yr_renovated', 'day',
                                                   'month', 'year', 'zip']),
                                                 ('categorical',
                                                  Pipeline(steps=[('SimpleImputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoding',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['city', 'country',
                                                   'state'])])),
                ('regression', LinearRegression())])

In [67]:
from sklearn.model_selection import train_test_split

In [68]:
df.columns

Index(['price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
       'waterfront', 'view', 'condition', 'sqft_above', 'sqft_basement',
       'yr_built', 'yr_renovated', 'city', 'country', 'day', 'month', 'year',
       'state', 'zip'],
      dtype='str')

In [69]:
X=df[['bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
       'waterfront', 'view', 'condition', 'sqft_above', 'sqft_basement',
       'yr_built', 'yr_renovated', 'city', 'country', 'day', 'month', 'year',
       'state', 'zip']]

In [70]:
Y=df['price']

In [71]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [72]:
model.fit(X_train,Y_train)

Pipeline(steps=[('feature',
                 ColumnTransformer(transformers=[('numeric',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer()),
                                                                  ('scaling',
                                                                   StandardScaler())]),
                                                  ['bedrooms', 'bathrooms',
                                                   'sqft_living', 'sqft_lot',
                                                   'floors', 'waterfront',
                                                   'view', 'condition',
                                                   'sqft_above',
                                                   'sqft_basement', 'yr_built',
                                                   'yr_renovated', 'day',
                                                   'month', 'year', 'zip']),
                                                 ('categorical',
                                                  Pipeline(steps=[('SimpleImputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoding',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['city', 'country',
                                                   'state'])])),
                ('regression', LinearRegression())])

In [73]:
y_predict=model.predict(X_test)

In [74]:
from sklearn.metrics import r2_score
r2_score(Y_test,y_predict)

0.6453481454307884

In [75]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae = mean_absolute_error(Y_test, y_predict)
rmse = np.sqrt(mean_squared_error(Y_test, y_predict))
r2 = r2_score(Y_test, y_predict)

print("MAE:", mae)
print("RMSE:", rmse)
print("R2:", r2)

MAE: 134374.10681485254
RMSE: 257276.93612390943
R2: 0.6453481454307884

In [76]:
from sklearn.svm import SVR

In [77]:
r=SVR(kernel='linear')