In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('heart_disease_cleaned.csv')

In [3]:
df.head()

,id,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
0,1,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,2,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,2
2,3,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,4,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,5,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0

In [4]:
def disease(value):
    if value==0:
        return 'No'
    else:
        return 'Yes'

In [5]:
df['disease']=df['num'].apply(disease)

In [6]:
df.head()

,id,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num,disease
0,1,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0,No
1,2,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,2,Yes
2,3,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1,Yes
3,4,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0,No
4,5,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0,No

In [7]:
df.isnull().sum()

id          0
age         0
sex         0
dataset     0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalch      0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
num         0
disease     0
dtype: int64

In [8]:
df=df.drop(columns=['num','id'])

In [9]:
df.head()

,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,disease
0,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,No
1,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,Yes
2,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,Yes
3,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,No
4,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,No

In [10]:
df.columns

Index(['age', 'sex', 'dataset', 'cp', 'trestbps', 'chol', 'fbs', 'restecg',
       'thalch', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'disease'],
      dtype='str')

In [11]:
df.isnull().sum()

age         0
sex         0
dataset     0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalch      0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
disease     0
dtype: int64

In [12]:
numerical_data = ['age', 'trestbps', 'chol', 'thalch', 'oldpeak','ca']
categorical_data = ['sex', 'dataset', 'cp', 'fbs', 'restecg','exang', 'thal']
ordinal_data = ['slope']

In [13]:
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder,LabelEncoder,StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

In [14]:
df['slope'].unique()

<ArrowStringArray>
['downsloping', 'flat', 'upsloping']
Length: 3, dtype: str

In [15]:
tranform=ColumnTransformer(transformers=[('nominal',OneHotEncoder(handle_unknown='ignore'),categorical_data),('scaling',StandardScaler(),numerical_data),('ordinal',OrdinalEncoder(categories=[['downsloping','flat','upsloping']]),ordinal_data)])

In [16]:
print(ordinal_data)

['slope']

In [17]:
tranform

ColumnTransformer(transformers=[('nominal',
                                 OneHotEncoder(handle_unknown='ignore'),
                                 ['sex', 'dataset', 'cp', 'fbs', 'restecg',
                                  'exang', 'thal']),
                                ('scaling', StandardScaler(),
                                 ['age', 'trestbps', 'chol', 'thalch',
                                  'oldpeak', 'ca']),
                                ('ordinal',
                                 OrdinalEncoder(categories=[['downsloping',
                                                             'flat',
                                                             'upsloping']]),
                                 ['slope'])])

In [18]:
df.columns

Index(['age', 'sex', 'dataset', 'cp', 'trestbps', 'chol', 'fbs', 'restecg',
       'thalch', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'disease'],
      dtype='str')

In [19]:
X=df[['age', 'sex', 'dataset', 'cp', 'trestbps', 'chol', 'fbs', 'restecg',
       'thalch', 'exang', 'oldpeak', 'slope', 'ca', 'thal']]

In [20]:
Y=df['disease']

In [21]:
X

,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal
0,63,Male,Cleveland,typical angina,145.00,233.0,True,lv hypertrophy,150.00,False,2.300,downsloping,0.0,fixed defect
1,67,Male,Cleveland,asymptomatic,160.00,286.0,False,lv hypertrophy,108.00,True,1.500,flat,3.0,normal
2,67,Male,Cleveland,asymptomatic,120.00,229.0,False,lv hypertrophy,129.00,True,2.600,flat,2.0,reversable defect
3,37,Male,Cleveland,non-anginal,130.00,250.0,False,normal,187.00,False,3.500,downsloping,0.0,normal
4,41,Female,Cleveland,atypical angina,130.00,204.0,False,lv hypertrophy,172.00,False,1.400,upsloping,0.0,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
914,54,Female,VA Long Beach,asymptomatic,127.00,333.0,True,st-t abnormality,154.00,False,0.000,flat,0.0,normal
915,62,Male,VA Long Beach,typical angina,143.06,139.0,False,st-t abnormality,119.94,True,2.042,flat,0.0,reversable defect
916,55,Male,VA Long Beach,asymptomatic,122.00,223.0,True,st-t abnormality,100.00,False,0.000,flat,1.0,fixed defect
917,58,Male,VA Long Beach,asymptomatic,150.81,385.0,True,lv hypertrophy,110.63,True,2.181,flat,0.0,reversable defect
918,62,Male,VA Long Beach,atypical angina,120.00,254.0,False,lv hypertrophy,93.00,True,0.000,flat,1.0,reversable defect

In [22]:
Y

0       No
1      Yes
2      Yes
3       No
4       No
      ...
914    Yes
915     No
916    Yes
917     No
918    Yes
Name: disease, Length: 919, dtype: str

In [23]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [24]:
X=tranform.fit_transform(X)

In [25]:
le=LabelEncoder()
Y=le.fit_transform(Y)

In [26]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [27]:
from sklearn.linear_model import LogisticRegression

In [28]:
lr=LogisticRegression()

In [29]:
lr.fit(X_train,Y_train)

LogisticRegression()

In [30]:
y_predict=lr.predict(X_test)

In [33]:
from sklearn.metrics import accuracy_score,r2_score

In [32]:

accuracy_score(Y_test,y_predict)*100

88.04347826086956

In [34]:
r2_score(Y_test,y_predict)

0.5119951778179626