In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
car=pd.read_csv('quikr_car.csv')

In [3]:
car.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [4]:
car.info()

<class 'pandas.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    str
 1   company     892 non-null    str
 2   year        892 non-null    str
 3   Price       892 non-null    str
 4   kms_driven  840 non-null    str
 5   fuel_type   837 non-null    str
dtypes: str(6)
memory usage: 92.3 KB

In [5]:
car.isnull().sum()

name           0
company        0
year           0
Price          0
kms_driven    52
fuel_type     55
dtype: int64

In [6]:
car['year'].unique()

<ArrowStringArray>
['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016', '2010',
 '2017', '2008', '2011', '2019', '2009', '2005', '2000',  '...', '150k',
 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs', 'sale', '1995', 'ara)',
 '2002', 'SELL', '2001', 'tion', 'odel', '2 bs', 'arry',  'Eon', 'o...',
 'ture',  'emi',  'car', 'able',  'no.', 'd...', 'SALE', 'digo', 'sell',
 'd Ex', 'n...', 'e...', 'D...', ', Ac', 'go .', 'k...', 'o c4', 'zire',
 'cent', 'Sumo',  'cab', 't xe',  'EV2', 'r...', 'zest']
Length: 61, dtype: str

In [7]:
car.columns

Index(['name', 'company', 'year', 'Price', 'kms_driven', 'fuel_type'], dtype='str')

In [8]:
car['fuel_type'].unique()

<ArrowStringArray>
['Petrol', 'Diesel', nan, 'LPG']
Length: 4, dtype: str

In [9]:
car['kms_driven'].unique()

<ArrowStringArray>
[  '45,000 kms',       '40 kms',   '22,000 kms',   '28,000 kms',
   '36,000 kms',   '59,000 kms',   '41,000 kms',   '25,000 kms',
   '24,530 kms',   '60,000 kms',
 ...
   '60,123 kms',   '38,900 kms', '1,37,495 kms',   '91,200 kms',
 '1,46,000 kms', '1,00,800 kms',    '2,100 kms',    '2,500 kms',
 '1,32,000 kms',       'Petrol']
Length: 259, dtype: str

In [10]:
car['company'].unique()

<ArrowStringArray>
[   'Hyundai',   'Mahindra',     'Maruti',       'Ford',      'Skoda',
       'Audi',     'Toyota',    'Renault',      'Honda',     'Datsun',
 'Mitsubishi',       'Tata', 'Volkswagen',          'I',  'Chevrolet',
       'Mini',        'BMW',     'Nissan',  'Hindustan',       'Fiat',
 'Commercial',     'MARUTI',      'Force',   'Mercedes',       'Land',
     'Yamaha',    'selling',     'URJENT',      'Swift',       'Used',
     'Jaguar',       'Jeep',       'tata',       'Sale',       'very',
      'Volvo',          'i',       '2012',       'Well',        'all',
          '7',          '9',    'scratch',     'urgent',       'sell',
       'TATA',        'Any',       'Tara']
Length: 48, dtype: str

In [11]:
car['Price'].unique()

<ArrowStringArray>
[       '80,000',      '4,25,000', 'Ask For Price',      '3,25,000',
      '5,75,000',      '1,75,000',      '1,90,000',      '8,30,000',
      '2,50,000',      '1,82,000',
 ...
        '42,000',      '1,89,000',      '1,62,000',        '35,999',
     '29,00,000',        '39,999',        '50,500',      '5,10,000',
      '8,60,000',      '5,00,001']
Length: 274, dtype: str

In [12]:
# what are the mistakes in the data set
# --> year has go many grabage value
# --> year is obj so we have to convert it into the int
# --> price have ask for price which should be removed
# --> kms_driven has kms in int
# --> kms_driven has nan value
# --> fuel_type has nan value
# --> we will keep the first three words from the name

In [13]:
# cleaning

In [14]:
car=car[car['year'].str.isnumeric()]

In [15]:
car['year']=car['year'].astype('int32')

In [16]:
car=car[car['Price']!='Ask For Price']

In [17]:
car['Price']=car['Price'].str.replace(',','')

In [18]:
car['Price']=car['Price'].astype('float32')

In [19]:
car['Price']

0       80000.0
1      425000.0
3      325000.0
4      575000.0
6      175000.0
         ...
886    300000.0
888    260000.0
889    390000.0
890    180000.0
891    160000.0
Name: Price, Length: 819, dtype: float32

In [20]:
car.columns

Index(['name', 'company', 'year', 'Price', 'kms_driven', 'fuel_type'], dtype='str')

In [21]:
car['kms_driven']=car['kms_driven'].str.split(' ').str.get(0).str.replace(',','')

In [22]:
car=car[car['kms_driven'].str.isnumeric()]

In [23]:
car['kms_driven']=car['kms_driven'].astype('int32')

In [24]:
car.info()

<class 'pandas.DataFrame'>
Index: 817 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        817 non-null    str
 1   company     817 non-null    str
 2   year        817 non-null    int32
 3   Price       817 non-null    float32
 4   kms_driven  817 non-null    int32
 5   fuel_type   816 non-null    str
dtypes: float32(1), int32(2), str(3)
memory usage: 64.6 KB

In [25]:
car=car[car['fuel_type'].isnull()!=True]

In [26]:
car.info()

<class 'pandas.DataFrame'>
Index: 816 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        816 non-null    str
 1   company     816 non-null    str
 2   year        816 non-null    int32
 3   Price       816 non-null    float32
 4   kms_driven  816 non-null    int32
 5   fuel_type   816 non-null    str
dtypes: float32(1), int32(2), str(3)
memory usage: 64.6 KB

In [27]:
car['name']=car['name'].str.split(' ').str.slice(0,3).str.join(' ')

In [28]:
car

                       name   company  year     Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000.0       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000.0          40    Diesel
3         Hyundai Grand i10   Hyundai  2014  325000.0       28000    Petrol
4    Ford EcoSport Titanium      Ford  2014  575000.0       36000    Diesel
6                 Ford Figo      Ford  2012  175000.0       41000    Diesel
..                      ...       ...   ...       ...         ...       ...
883      Maruti Suzuki Ritz    Maruti  2011  270000.0       50000    Petrol
885          Tata Indica V2      Tata  2009  110000.0       30000    Diesel
886    Toyota Corolla Altis    Toyota  2009  300000.0      132000    Petrol
888            Tata Zest XM      Tata  2018  260000.0       27000    Diesel
889      Mahindra Quanto C8  Mahindra  2013  390000.0       40000    Diesel

[816 rows x 6 columns]

In [29]:
car.reset_index(drop=True)

                       name   company  year     Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000.0       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000.0          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000.0       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000.0       36000    Diesel
4                 Ford Figo      Ford  2012  175000.0       41000    Diesel
..                      ...       ...   ...       ...         ...       ...
811      Maruti Suzuki Ritz    Maruti  2011  270000.0       50000    Petrol
812          Tata Indica V2      Tata  2009  110000.0       30000    Diesel
813    Toyota Corolla Altis    Toyota  2009  300000.0      132000    Petrol
814            Tata Zest XM      Tata  2018  260000.0       27000    Diesel
815      Mahindra Quanto C8  Mahindra  2013  390000.0       40000    Diesel

[816 rows x 6 columns]

In [30]:
car.head()

                     name   company  year     Price  kms_driven fuel_type
0     Hyundai Santro Xing   Hyundai  2007   80000.0       45000    Petrol
1     Mahindra Jeep CL550  Mahindra  2006  425000.0          40    Diesel
3       Hyundai Grand i10   Hyundai  2014  325000.0       28000    Petrol
4  Ford EcoSport Titanium      Ford  2014  575000.0       36000    Diesel
6               Ford Figo      Ford  2012  175000.0       41000    Diesel

In [31]:
car.describe()

              year         Price     kms_driven
count   816.000000  8.160000e+02     816.000000
mean   2012.444853  4.117177e+05   46275.531863
std       4.002992  4.751844e+05   34297.428044
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   27000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.912500e+05   56818.500000
max    2019.000000  8.500003e+06  400000.000000

In [32]:
car=car[car['Price']<6000000].reset_index(drop=True)

In [33]:
car

                       name   company  year     Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000.0       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000.0          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000.0       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000.0       36000    Diesel
4                 Ford Figo      Ford  2012  175000.0       41000    Diesel
..                      ...       ...   ...       ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011  270000.0       50000    Petrol
811          Tata Indica V2      Tata  2009  110000.0       30000    Diesel
812    Toyota Corolla Altis    Toyota  2009  300000.0      132000    Petrol
813            Tata Zest XM      Tata  2018  260000.0       27000    Diesel
814      Mahindra Quanto C8  Mahindra  2013  390000.0       40000    Diesel

[815 rows x 6 columns]

In [34]:
car.to_csv("cleaned_car_dataset.csv", index=False)

In [35]:
car.columns

Index(['name', 'company', 'year', 'Price', 'kms_driven', 'fuel_type'], dtype='str')

In [36]:
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [37]:
car.head()

                     name   company  year     Price  kms_driven fuel_type
0     Hyundai Santro Xing   Hyundai  2007   80000.0       45000    Petrol
1     Mahindra Jeep CL550  Mahindra  2006  425000.0          40    Diesel
2       Hyundai Grand i10   Hyundai  2014  325000.0       28000    Petrol
3  Ford EcoSport Titanium      Ford  2014  575000.0       36000    Diesel
4               Ford Figo      Ford  2012  175000.0       41000    Diesel

In [38]:
numeric_data=['year','kms_driven']
nominal_data=['name','company','fuel_type']

In [39]:
numeric_pipeline=Pipeline(steps=[('scaling',StandardScaler())])
nominal_pipeline=Pipeline(steps=[('encoding',OneHotEncoder(handle_unknown='ignore'))])

In [40]:
tranform=ColumnTransformer(transformers=[('numeric',numeric_pipeline,numeric_data),('nominal',nominal_pipeline,nominal_data)])

In [41]:
# Complete ML Pipeline
model = Pipeline(
    steps=[
        ('preprocessing', tranform),
        ('regressor', LinearRegression())
    ]
)

In [45]:
X = car[['name', 'company', 'year', 'kms_driven', 'fuel_type']]
y = car['Price']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model.fit(X_train, y_train)
Y_predict=model.predict(X_test)

import pickle
# SAVE THE PIPELINE
pickle.dump(model, open("LinearRegressionModel.pkl", "wb"))

In [44]:
from sklearn.metrics import r2_score

In [46]:
r2_score(y_test,Y_predict)

0.6424409705058906