In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv('Student Depression Dataset.csv')

In [3]:
data

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [4]:
data.head(10)

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
5,33,Male,29.0,Pune,Student,2.0,0.0,5.70,3.0,0.0,Less than 5 hours,Healthy,PhD,No,4.0,1.0,No,0
6,52,Male,30.0,Thane,Student,3.0,0.0,9.54,4.0,0.0,7-8 hours,Healthy,BSc,No,1.0,2.0,No,0
7,56,Female,30.0,Chennai,Student,2.0,0.0,8.04,4.0,0.0,Less than 5 hours,Unhealthy,Class 12,No,0.0,1.0,Yes,0
8,59,Male,28.0,Nagpur,Student,3.0,0.0,9.79,1.0,0.0,7-8 hours,Moderate,B.Ed,Yes,12.0,3.0,No,1
9,62,Male,31.0,Nashik,Student,2.0,0.0,8.38,3.0,0.0,Less than 5 hours,Moderate,LLB,Yes,2.0,5.0,No,1

In [5]:
data.tail(10)

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
27891,140645,Female,28.0,Thane,Student,4.0,0.0,7.77,3.0,0.0,Less than 5 hours,Unhealthy,MSc,No,2.0,5.0,No,1
27892,140669,Female,20.0,Indore,Student,3.0,0.0,7.72,5.0,0.0,Less than 5 hours,Moderate,Class 12,Yes,8.0,1.0,No,0
27893,140672,Female,24.0,Hyderabad,Student,3.0,0.0,6.02,2.0,0.0,7-8 hours,Moderate,B.Arch,No,8.0,2.0,No,0
27894,140681,Male,23.0,Srinagar,Student,3.0,0.0,6.00,2.0,0.0,More than 8 hours,Healthy,MBBS,Yes,12.0,4.0,No,0
27895,140684,Male,31.0,Lucknow,Student,2.0,0.0,7.27,5.0,0.0,7-8 hours,Moderate,B.Com,Yes,6.0,1.0,Yes,0
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [6]:
data.shape

(27901, 18)

In [7]:
data.dtypes

id                                         int64
Gender                                       str
Age                                      float64
City                                         str
Profession                                   str
Academic Pressure                        float64
Work Pressure                            float64
CGPA                                     float64
Study Satisfaction                       float64
Job Satisfaction                         float64
Sleep Duration                               str
Dietary Habits                               str
Degree                                       str
Have you ever had suicidal thoughts ?        str
Work/Study Hours                         float64
Financial Stress                         float64
Family History of Mental Illness             str
Depression                                 int64
dtype: object

In [8]:
data.columns

Index(['id', 'Gender', 'Age', 'City', 'Profession', 'Academic Pressure',
       'Work Pressure', 'CGPA', 'Study Satisfaction', 'Job Satisfaction',
       'Sleep Duration', 'Dietary Habits', 'Degree',
       'Have you ever had suicidal thoughts ?', 'Work/Study Hours',
       'Financial Stress', 'Family History of Mental Illness', 'Depression'],
      dtype='str')

In [9]:
data.isnull().sum()

id                                       0
Gender                                   0
Age                                      0
City                                     0
Profession                               0
Academic Pressure                        0
Work Pressure                            0
CGPA                                     0
Study Satisfaction                       0
Job Satisfaction                         0
Sleep Duration                           0
Dietary Habits                           0
Degree                                   0
Have you ever had suicidal thoughts ?    0
Work/Study Hours                         0
Financial Stress                         3
Family History of Mental Illness         0
Depression                               0
dtype: int64

In [10]:
data.describe()

,id,Age,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Work/Study Hours,Financial Stress,Depression
count,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27898.000000,27901.000000
mean,70442.149421,25.822300,3.141214,0.000430,7.656104,2.943837,0.000681,7.156984,3.139867,0.585499
std,40641.175216,4.905687,1.381465,0.043992,1.470707,1.361148,0.044394,3.707642,1.437347,0.492645
min,2.000000,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
25%,35039.000000,21.000000,2.000000,0.000000,6.290000,2.000000,0.000000,4.000000,2.000000,0.000000
50%,70684.000000,25.000000,3.000000,0.000000,7.770000,3.000000,0.000000,8.000000,3.000000,1.000000
75%,105818.000000,30.000000,4.000000,0.000000,8.920000,4.000000,0.000000,10.000000,4.000000,1.000000
max,140699.000000,59.000000,5.000000,5.000000,10.000000,5.000000,4.000000,12.000000,5.000000,1.000000

In [11]:
data.duplicated().sum()

np.int64(0)

In [12]:
data.drop_duplicates()

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [13]:
data['Age'].mean()

np.float64(25.82230027597577)

In [14]:
data['Age'].max()

np.float64(59.0)

In [15]:
data['Age'].min()

np.float64(18.0)

In [16]:
(data['Gender']=='Male').sum()

np.int64(15547)

In [17]:
(data['Gender']=='Female').sum()

np.int64(12354)

In [18]:
data['CGPA'].mean()

np.float64(7.65610417189348)

In [19]:
data.loc[data['CGPA'].idxmax()]

id                                                    2078
Gender                                                Male
Age                                                   25.0
City                                                 Patna
Profession                                         Student
Academic Pressure                                      3.0
Work Pressure                                          0.0
CGPA                                                  10.0
Study Satisfaction                                     3.0
Job Satisfaction                                       0.0
Sleep Duration                           More than 8 hours
Dietary Habits                                   Unhealthy
Degree                                                 BBA
Have you ever had suicidal thoughts ?                  Yes
Work/Study Hours                                      10.0
Financial Stress                                       3.0
Family History of Mental Illness                       Yes
Depression                                               0
Name: 417, dtype: object

In [20]:
data.loc[data['CGPA'].idxmin()]

id                                           21880
Gender                                        Male
Age                                           38.0
City                                       Chennai
Profession                                 Student
Academic Pressure                              0.0
Work Pressure                                  5.0
CGPA                                           0.0
Study Satisfaction                             0.0
Job Satisfaction                               4.0
Sleep Duration                           5-6 hours
Dietary Habits                             Healthy
Degree                                    Class 12
Have you ever had suicidal thoughts ?           No
Work/Study Hours                               2.0
Financial Stress                               3.0
Family History of Mental Illness                No
Depression                                       0
Name: 4365, dtype: object

In [21]:
max_cgpa=data['CGPA'].max()
data[data['CGPA']==max_cgpa]

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
417,2078,Male,25.0,Patna,Student,3.0,0.0,10.0,3.0,0.0,More than 8 hours,Unhealthy,BBA,Yes,10.0,3.0,Yes,0
1011,5220,Male,19.0,Indore,Student,1.0,0.0,10.0,3.0,0.0,More than 8 hours,Moderate,Class 12,Yes,2.0,1.0,No,0
1929,9885,Female,22.0,Kanpur,Student,1.0,0.0,10.0,4.0,0.0,Less than 5 hours,Moderate,M.Com,No,7.0,1.0,Yes,0
2542,12972,Male,26.0,Patna,Student,3.0,0.0,10.0,1.0,0.0,Less than 5 hours,Moderate,BSc,Yes,3.0,3.0,Yes,0
2581,13170,Female,25.0,Lucknow,Student,3.0,0.0,10.0,2.0,0.0,More than 8 hours,Unhealthy,B.Ed,Yes,0.0,5.0,No,1
3126,15800,Female,26.0,Patna,Student,5.0,0.0,10.0,1.0,0.0,More than 8 hours,Unhealthy,B.Pharm,Yes,6.0,5.0,Yes,1
3174,15991,Female,32.0,Kanpur,Student,2.0,0.0,10.0,4.0,0.0,Less than 5 hours,Healthy,M.Ed,Yes,3.0,2.0,Yes,0
3465,17340,Female,32.0,Kanpur,Student,5.0,0.0,10.0,2.0,0.0,7-8 hours,Healthy,BE,Yes,2.0,2.0,Yes,0
4301,21573,Male,23.0,Patna,Student,1.0,0.0,10.0,1.0,0.0,Less than 5 hours,Healthy,BSc,Yes,10.0,1.0,Yes,0
4488,22499,Male,33.0,Patna,Student,4.0,0.0,10.0,1.0,0.0,Less than 5 hours,Moderate,BSc,Yes,8.0,5.0,No,1
4986,24975,Female,31.0,Chennai,Student,3.0,0.0,10.0,5.0,0.0,5-6 hours,Moderate,M.Ed,Yes,12.0,1.0,Yes,1
5050,25353,Male,32.0,Nashik,Student,1.0,0.0,10.0,2.0,0.0,Less than 5 hours,Moderate,LLB,Yes,12.0,3.0,Yes,1
5075,25482,Male,29.0,Nagpur,Student,4.0,0.0,10.0,2.0,0.0,7-8 hours,Unhealthy,MD,Yes,7.0,5.0,Yes,1
5257,26545,Male,28.0,Indore,Student,4.0,0.0,10.0,3.0,0.0,More than 8 hours,Unhealthy,B.Com,No,5.0,2.0,No,0
5330,26892,Male,27.0,Bhopal,Student,3.0,0.0,10.0,5.0,0.0,5-6 hours,Unhealthy,MSc,Yes,8.0,5.0,Yes,1
5563,28045,Male,27.0,Patna,Student,3.0,0.0,10.0,4.0,0.0,More than 8 hours,Healthy,B.Tech,Yes,6.0,1.0,No,0
6467,32401,Male,33.0,Patna,Student,4.0,0.0,10.0,3.0,0.0,More than 8 hours,Healthy,BSc,Yes,10.0,4.0,Yes,0
6522,32697,Female,28.0,Varanasi,Student,3.0,0.0,10.0,4.0,0.0,Less than 5 hours,Unhealthy,MSc,Yes,12.0,5.0,Yes,1
6935,34831,Male,32.0,Bangalore,Student,5.0,0.0,10.0,2.0,0.0,More than 8 hours,Moderate,MBBS,Yes,2.0,4.0,Yes,1
7564,38077,Male,21.0,Hyderabad,Student,5.0,0.0,10.0,4.0,0.0,More than 8 hours,Unhealthy,MSc,Yes,5.0,5.0,Yes,1
8149,41031,Male,22.0,Patna,Student,3.0,0.0,10.0,1.0,0.0,7-8 hours,Moderate,BHM,No,4.0,1.0,No,0
8331,41928,Male,32.0,Meerut,Student,5.0,0.0,10.0,1.0,0.0,More than 8 hours,Moderate,B.Pharm,Yes,11.0,5.0,No,1
9904,50051,Male,27.0,Kalyan,Student,4.0,0.0,10.0,3.0,0.0,7-8 hours,Moderate,MSc,Yes,8.0,2.0,No,0
10244,51831,Female,21.0,Kolkata,Student,3.0,0.0,10.0,1.0,0.0,Less than 5 hours,Moderate,BA,No,3.0,5.0,No,1
11255,57003,Male,28.0,Srinagar,Student,3.0,0.0,10.0,2.0,0.0,5-6 hours,Unhealthy,BHM,Yes,11.0,5.0,No,1
11617,58690,Male,18.0,Surat,Student,2.0,0.0,10.0,3.0,0.0,7-8 hours,Unhealthy,Class 12,Yes,8.0,4.0,Yes,1
12426,62789,Female,29.0,Surat,Student,1.0,0.0,10.0,1.0,0.0,Less than 5 hours,Unhealthy,LLB,No,8.0,3.0,No,0
13699,69366,Male,26.0,Indore,Student,5.0,0.0,10.0,4.0,0.0,Less than 5 hours,Unhealthy,B.Com,No,12.0,3.0,No,1
14942,75373,Male,25.0,Srinagar,Student,5.0,0.0,10.0,5.0,0.0,5-6 hours,Healthy,M.Tech,Yes,4.0,4.0,Yes,0
14962,75448,Male,23.0,Mumbai,Student,4.0,0.0,10.0,4.0,0.0,More than 8 hours,Moderate,LLB,Yes,1.0,5.0,Yes,1
15281,77074,Female,20.0,Delhi,Student,4.0,0.0,10.0,5.0,0.0,Less than 5 hours,Moderate,Class 12,No,11.0,5.0,No,1
15463,78012,Male,23.0,Patna,Student,1.0,0.0,10.0,3.0,0.0,More than 8 hours,Healthy,BSc,No,12.0,3.0,No,0
16763,84763,Male,30.0,Surat,Student,3.0,0.0,10.0,1.0,0.0,5-6 hours,Moderate,MD,Yes,10.0,4.0,No,1
17038,86332,Male,26.0,Indore,Student,2.0,0.0,10.0,3.0,0.0,7-8 hours,Unhealthy,B.Com,Yes,1.0,4.0,Yes,1
18097,91604,Male,23.0,Patna,Student,3.0,0.0,10.0,4.0,0.0,More than 8 hours,Healthy,BSc,No,1.0,1.0,No,0
19228,97393,Male,23.0,Patna,Student,3.0,0.0,10.0,1.0,0.0,Less than 5 hours,Healthy,BSc,No,1.0,3.0,No,0
19602,99337,Male,24.0,Patna,Student,3.0,0.0,10.0,1.0,0.0,7-8 hours,Unhealthy,B.Arch,Yes,0.0,5.0,No,1
19691,99779,Male,25.0,Lucknow,Student,3.0,0.0,10.0,3.0,0.0,More than 8 hours,Unhealthy,PhD,Yes,6.0,4.0,No,1
20286,102728,Male,33.0,Patna,Student,4.0,0.0,10.0,3.0,0.0,Less than 5 hours,Moderate,BSc,Yes,4.0,1.0,Yes,0
20386,103222,Male,23.0,Patna,Student,3.0,0.0,10.0,1.0,0.0,Less than 5 hours,Moderate,BSc,Yes,8.0,5.0,No,1
20572,104137,Female,19.0,Srinagar,Student,1.0,0.0,10.0,5.0,0.0,More than 8 hours,Unhealthy,Class 12,No,6.0,1.0,Yes,0
20649,104508,Male,33.0,Nashik,Student,1.0,0.0,10.0,1.0,0.0,5-6 hours,Healthy,B.Tech,No,8.0,2.0,Yes,0
20942,105897,Female,25.0,Chennai,Student,1.0,0.0,10.0,2.0,0.0,7-8 hours,Moderate,MA,No,9.0,4.0,No,0
22259,112284,Female,22.0,Hyderabad,Student,1.0,0.0,10.0,4.0,0.0,5-6 hours,Healthy,BBA,No,2.0,4.0,Yes,0
22789,114938,Male,27.0,Vadodara,Student,2.0,0.0,10.0,4.0,0.0,More than 8 hours,Healthy,BBA,Yes,3.0,3.0,Yes,0
22894,115439,Male,34.0,Lucknow,Student,5.0,0.0,10.0,3.0,0.0,Less than 5 hours,Moderate,B.Com,Yes,8.0,1.0,No,0
23336,117626,Female,31.0,Ahmedabad,Student,5.0,0.0,10.0,4.0,0.0,7-8 hours,Healthy,BE,Yes,6.0,1.0,Yes,0
23783,119828,Male,27.0,Varanasi,Student,5.0,0.0,10.0,4.0,0.0,5-6 hours,Healthy,B.Arch,Yes,4.0,5.0,Yes,1
24193,121769,Male,22.0,Kolkata,Student,5.0,0.0,10.0,3.0,0.0,More than 8 hours,Moderate,B.Com,Yes,8.0,5.0,No,1
24608,124003,Male,26.0,Delhi,Student,4.0,0.0,10.0,3.0,0.0,More than 8 hours,Unhealthy,BHM,No,6.0,1.0,No,0
25171,126805,Female,34.0,Kanpur,Student,3.0,0.0,10.0,4.0,0.0,5-6 hours,Healthy,BCA,No,3.0,1.0,No,0
25188,126894,Female,24.0,Kolkata,Student,2.0,0.0,10.0,5.0,0.0,Less than 5 hours,Moderate,B.Ed,Yes,8.0,2.0,No,1
25265,127309,Female,25.0,Patna,Student,5.0,0.0,10.0,3.0,0.0,5-6 hours,Healthy,LLM,No,3.0,4.0,Yes,1
25337,127641,Male,29.0,Indore,Student,4.0,0.0,10.0,4.0,0.0,Less than 5 hours,Unhealthy,BCA,Yes,11.0,2.0,Yes,1
25401,127981,Male,26.0,Visakhapatnam,Student,4.0,0.0,10.0,1.0,0.0,More than 8 hours,Unhealthy,BHM,Yes,9.0,5.0,No,1
25691,129507,Male,23.0,Patna,Student,4.0,0.0,10.0,3.0,0.0,Less than 5 hours,Moderate,BSc,Yes,10.0,3.0,Yes,1
27445,138365,Male,26.0,Pune,Student,4.0,0.0,10.0,1.0,0.0,Less than 5 hours,Moderate,PhD,Yes,11.0,5.0,No,1
27678,139549,Female,30.0,Ludhiana,Student,3.0,0.0,10.0,1.0,0.0,5-6 hours,Healthy,PhD,Yes,3.0,1.0,No,0

In [22]:
data.sort_values(by='CGPA',ascending=False).head(5)

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
417,2078,Male,25.0,Patna,Student,3.0,0.0,10.0,3.0,0.0,More than 8 hours,Unhealthy,BBA,Yes,10.0,3.0,Yes,0
3126,15800,Female,26.0,Patna,Student,5.0,0.0,10.0,1.0,0.0,More than 8 hours,Unhealthy,B.Pharm,Yes,6.0,5.0,Yes,1
18097,91604,Male,23.0,Patna,Student,3.0,0.0,10.0,4.0,0.0,More than 8 hours,Healthy,BSc,No,1.0,1.0,No,0
6935,34831,Male,32.0,Bangalore,Student,5.0,0.0,10.0,2.0,0.0,More than 8 hours,Moderate,MBBS,Yes,2.0,4.0,Yes,1
27445,138365,Male,26.0,Pune,Student,4.0,0.0,10.0,1.0,0.0,Less than 5 hours,Moderate,PhD,Yes,11.0,5.0,No,1

In [23]:
data.sort_values(by='CGPA').head(5)

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
11489,58062,Female,32.0,Vadodara,Student,5.0,0.0,0.0,0.0,0.0,Less than 5 hours,Unhealthy,Class 12,Yes,11.0,5.0,No,1
21805,110097,Male,34.0,Pune,Student,1.0,0.0,0.0,5.0,0.0,Less than 5 hours,Unhealthy,M.Ed,Yes,10.0,3.0,Yes,0
26719,134830,Female,24.0,Meerut,Student,0.0,0.0,0.0,0.0,2.0,More than 8 hours,Unhealthy,Class 12,No,0.0,5.0,No,0
10407,52737,Male,28.0,Vadodara,Student,3.0,0.0,0.0,4.0,0.0,Less than 5 hours,Healthy,BBA,No,12.0,2.0,No,0
20913,105773,Male,18.0,Ahmedabad,Student,0.0,0.0,0.0,0.0,1.0,Less than 5 hours,Moderate,Class 12,Yes,9.0,5.0,No,1

In [24]:
data.groupby('Gender')['CGPA'].mean()

Gender
Female    7.596645
Male      7.703352
Name: CGPA, dtype: float64

In [25]:
data['Profession'].value_counts()

Profession
Student                   27870
Architect                     8
Teacher                       6
Digital Marketer              3
Content Writer                2
Chef                          2
Doctor                        2
Pharmacist                    2
Civil Engineer                1
UX/UI Designer                1
Educational Consultant        1
Manager                       1
Lawyer                        1
Entrepreneur                  1
Name: count, dtype: int64

In [26]:
data['Gender'].value_counts()

Gender
Male      15547
Female    12354
Name: count, dtype: int64

In [27]:
data['City'].value_counts()

City
Kalyan                1570
Srinagar              1372
Hyderabad             1340
Vasai-Virar           1290
Lucknow               1155
Thane                 1139
Ludhiana              1111
Agra                  1094
Surat                 1078
Kolkata               1066
Jaipur                1036
Patna                 1007
Visakhapatnam          969
Pune                   968
Ahmedabad              951
Bhopal                 934
Chennai                885
Meerut                 825
Rajkot                 816
Delhi                  768
Bangalore              767
Ghaziabad              745
Mumbai                 699
Vadodara               694
Varanasi               685
Nagpur                 651
Indore                 643
Kanpur                 609
Nashik                 547
Faridabad              461
Saanvi                   2
Bhavna                   2
City                     2
Harsha                   2
M.Tech                   1
Less Delhi               1
3.0                      1
Less than 5 Kalyan       1
Mira                     1
Vaanya                   1
Gaurav                   1
Harsh                    1
Reyansh                  1
Kibara                   1
Rashi                    1
ME                       1
M.Com                    1
Nalyan                   1
Mihir                    1
Nalini                   1
Nandini                  1
Khaziabad                1
Name: count, dtype: int64

In [28]:
data[data['CGPA']>8]

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
6,52,Male,30.0,Thane,Student,3.0,0.0,9.54,4.0,0.0,7-8 hours,Healthy,BSc,No,1.0,2.0,No,0
7,56,Female,30.0,Chennai,Student,2.0,0.0,8.04,4.0,0.0,Less than 5 hours,Unhealthy,Class 12,No,0.0,1.0,Yes,0
8,59,Male,28.0,Nagpur,Student,3.0,0.0,9.79,1.0,0.0,7-8 hours,Moderate,B.Ed,Yes,12.0,3.0,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27885,140597,Female,19.0,Mumbai,Student,2.0,0.0,9.21,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,3.0,2.0,No,0
27886,140601,Female,22.0,Jaipur,Student,5.0,0.0,9.25,4.0,0.0,More than 8 hours,Unhealthy,BBA,Yes,8.0,3.0,No,1
27887,140624,Male,32.0,Rajkot,Student,4.0,0.0,9.19,1.0,0.0,5-6 hours,Healthy,MSc,No,7.0,4.0,Yes,1
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [29]:
data[data['Depression']==1]

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
8,59,Male,28.0,Nagpur,Student,3.0,0.0,9.79,1.0,0.0,7-8 hours,Moderate,B.Ed,Yes,12.0,3.0,No,1
9,62,Male,31.0,Nashik,Student,2.0,0.0,8.38,3.0,0.0,Less than 5 hours,Moderate,LLB,Yes,2.0,5.0,No,1
10,83,Male,24.0,Nagpur,Student,3.0,0.0,6.10,3.0,0.0,5-6 hours,Moderate,Class 12,Yes,11.0,1.0,Yes,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27887,140624,Male,32.0,Rajkot,Student,4.0,0.0,9.19,1.0,0.0,5-6 hours,Healthy,MSc,No,7.0,4.0,Yes,1
27888,140630,Male,19.0,Kolkata,Student,4.0,0.0,7.13,1.0,0.0,More than 8 hours,Moderate,Class 12,No,10.0,2.0,No,1
27891,140645,Female,28.0,Thane,Student,4.0,0.0,7.77,3.0,0.0,Less than 5 hours,Unhealthy,MSc,No,2.0,5.0,No,1
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [30]:
data['Sleep Duration'].value_counts()

Sleep Duration
Less than 5 hours    8310
7-8 hours            7346
5-6 hours            6183
More than 8 hours    6044
Others                 18
Name: count, dtype: int64

In [31]:
data[data['Sleep Duration']=='Less than 5 hours']

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
5,33,Male,29.0,Pune,Student,2.0,0.0,5.70,3.0,0.0,Less than 5 hours,Healthy,PhD,No,4.0,1.0,No,0
7,56,Female,30.0,Chennai,Student,2.0,0.0,8.04,4.0,0.0,Less than 5 hours,Unhealthy,Class 12,No,0.0,1.0,Yes,0
9,62,Male,31.0,Nashik,Student,2.0,0.0,8.38,3.0,0.0,Less than 5 hours,Moderate,LLB,Yes,2.0,5.0,No,1
11,91,Male,33.0,Vadodara,Student,3.0,0.0,7.03,4.0,0.0,Less than 5 hours,Healthy,BE,Yes,10.0,2.0,Yes,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27891,140645,Female,28.0,Thane,Student,4.0,0.0,7.77,3.0,0.0,Less than 5 hours,Unhealthy,MSc,No,2.0,5.0,No,1
27892,140669,Female,20.0,Indore,Student,3.0,0.0,7.72,5.0,0.0,Less than 5 hours,Moderate,Class 12,Yes,8.0,1.0,No,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [32]:
data[data['Academic Pressure']>3]

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
12,94,Male,27.0,Kalyan,Student,5.0,0.0,7.04,1.0,0.0,Less than 5 hours,Moderate,M.Tech,No,10.0,1.0,Yes,1
14,103,Female,19.0,Kalyan,Student,5.0,0.0,5.64,5.0,0.0,Less than 5 hours,Moderate,Class 12,Yes,4.0,5.0,Yes,1
16,120,Male,25.0,Nashik,Student,5.0,0.0,6.51,2.0,0.0,Less than 5 hours,Unhealthy,M.Ed,Yes,2.0,5.0,Yes,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27888,140630,Male,19.0,Kolkata,Student,4.0,0.0,7.13,1.0,0.0,More than 8 hours,Moderate,Class 12,No,10.0,2.0,No,1
27891,140645,Female,28.0,Thane,Student,4.0,0.0,7.77,3.0,0.0,Less than 5 hours,Unhealthy,MSc,No,2.0,5.0,No,1
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [33]:
data[(data['CGPA']>8) & (data['Depression']==1)]

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
8,59,Male,28.0,Nagpur,Student,3.0,0.0,9.79,1.0,0.0,7-8 hours,Moderate,B.Ed,Yes,12.0,3.0,No,1
9,62,Male,31.0,Nashik,Student,2.0,0.0,8.38,3.0,0.0,Less than 5 hours,Moderate,LLB,Yes,2.0,5.0,No,1
15,106,Male,29.0,Srinagar,Student,3.0,0.0,8.58,3.0,0.0,More than 8 hours,Moderate,M.Tech,Yes,10.0,2.0,Yes,1
19,145,Male,25.0,Kalyan,Student,3.0,0.0,9.93,3.0,0.0,5-6 hours,Moderate,B.Ed,No,8.0,3.0,Yes,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27874,140530,Female,19.0,Ghaziabad,Student,3.0,0.0,9.93,3.0,0.0,7-8 hours,Unhealthy,Class 12,Yes,4.0,5.0,No,1
27878,140547,Male,27.0,Indore,Student,4.0,0.0,9.88,3.0,0.0,7-8 hours,Unhealthy,B.Com,Yes,12.0,2.0,Yes,1
27886,140601,Female,22.0,Jaipur,Student,5.0,0.0,9.25,4.0,0.0,More than 8 hours,Unhealthy,BBA,Yes,8.0,3.0,No,1
27887,140624,Male,32.0,Rajkot,Student,4.0,0.0,9.19,1.0,0.0,5-6 hours,Healthy,MSc,No,7.0,4.0,Yes,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [34]:
data[(data['Gender']=='Female') & (data['Depression']==1)]

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
14,103,Female,19.0,Kalyan,Student,5.0,0.0,5.64,5.0,0.0,Less than 5 hours,Moderate,Class 12,Yes,4.0,5.0,Yes,1
17,132,Female,20.0,Ahmedabad,Student,5.0,0.0,7.25,3.0,0.0,5-6 hours,Healthy,Class 12,Yes,10.0,3.0,No,1
22,166,Female,25.0,Ahmedabad,Student,3.0,0.0,5.57,3.0,0.0,More than 8 hours,Unhealthy,MSc,Yes,10.0,5.0,No,1
25,176,Female,20.0,Mumbai,Student,5.0,0.0,8.58,5.0,0.0,7-8 hours,Moderate,Class 12,No,2.0,2.0,Yes,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27875,140531,Female,23.0,Faridabad,Student,3.0,0.0,5.38,4.0,0.0,7-8 hours,Unhealthy,BSc,Yes,12.0,4.0,No,1
27883,140584,Female,22.0,Kanpur,Student,4.0,0.0,6.61,2.0,0.0,More than 8 hours,Unhealthy,M.Com,Yes,6.0,5.0,No,1
27886,140601,Female,22.0,Jaipur,Student,5.0,0.0,9.25,4.0,0.0,More than 8 hours,Unhealthy,BBA,Yes,8.0,3.0,No,1
27891,140645,Female,28.0,Thane,Student,4.0,0.0,7.77,3.0,0.0,Less than 5 hours,Unhealthy,MSc,No,2.0,5.0,No,1
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1

In [35]:
data[(data['Gender']=='Male') & (data['Depression']==1)]

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
8,59,Male,28.0,Nagpur,Student,3.0,0.0,9.79,1.0,0.0,7-8 hours,Moderate,B.Ed,Yes,12.0,3.0,No,1
9,62,Male,31.0,Nashik,Student,2.0,0.0,8.38,3.0,0.0,Less than 5 hours,Moderate,LLB,Yes,2.0,5.0,No,1
10,83,Male,24.0,Nagpur,Student,3.0,0.0,6.10,3.0,0.0,5-6 hours,Moderate,Class 12,Yes,11.0,1.0,Yes,1
12,94,Male,27.0,Kalyan,Student,5.0,0.0,7.04,1.0,0.0,Less than 5 hours,Moderate,M.Tech,No,10.0,1.0,Yes,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27881,140564,Male,27.0,Surat,Student,4.0,0.0,5.16,4.0,0.0,Less than 5 hours,Moderate,M.Pharm,Yes,6.0,2.0,Yes,1
27884,140594,Male,18.0,Meerut,Student,5.0,0.0,6.25,3.0,0.0,7-8 hours,Unhealthy,Class 12,No,11.0,2.0,Yes,1
27887,140624,Male,32.0,Rajkot,Student,4.0,0.0,9.19,1.0,0.0,5-6 hours,Healthy,MSc,No,7.0,4.0,Yes,1
27888,140630,Male,19.0,Kolkata,Student,4.0,0.0,7.13,1.0,0.0,More than 8 hours,Moderate,Class 12,No,10.0,2.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [36]:
data[data['Age']>25]

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
5,33,Male,29.0,Pune,Student,2.0,0.0,5.70,3.0,0.0,Less than 5 hours,Healthy,PhD,No,4.0,1.0,No,0
6,52,Male,30.0,Thane,Student,3.0,0.0,9.54,4.0,0.0,7-8 hours,Healthy,BSc,No,1.0,2.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27895,140684,Male,31.0,Lucknow,Student,2.0,0.0,7.27,5.0,0.0,7-8 hours,Moderate,B.Com,Yes,6.0,1.0,Yes,0
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [37]:
data.groupby('Gender')['CGPA'].mean()

Gender
Female    7.596645
Male      7.703352
Name: CGPA, dtype: float64

In [38]:
data['Profession'].value_counts()

Profession
Student                   27870
Architect                     8
Teacher                       6
Digital Marketer              3
Content Writer                2
Chef                          2
Doctor                        2
Pharmacist                    2
Civil Engineer                1
UX/UI Designer                1
Educational Consultant        1
Manager                       1
Lawyer                        1
Entrepreneur                  1
Name: count, dtype: int64

In [39]:
data.groupby('Gender')['CGPA'].max()

Gender
Female    10.0
Male      10.0
Name: CGPA, dtype: float64

In [40]:
data.groupby('Gender')['Age'].min()

Gender
Female    18.0
Male      18.0
Name: Age, dtype: float64